const IDS=['lastName','firstMiddleName','age','date','place','height','build','hair','eyes','special','jacket','pants','shoes','carrying','actual'];
const $=id=>document.getElementById(id);
const canvas=$('poster'),ctx=canvas.getContext('2d');
let bg=new Image(),photoImg=null,deferredPrompt=null;
bg.src='template.jpg';
bg.onload=render;
function val(id){return $(id).value.trim()}
function save(){const d={};IDS.forEach(id=>d[id]=$(id).value);localStorage.setItem('kpc-draft',JSON.stringify(d))}
function load(){try{const d=JSON.parse(localStorage.getItem('kpc-draft')||'{}');IDS.forEach(id=>{if(d[id]!=null)$(id).value=d[id]})}catch{} if(!val('actual')) $('actual').value=new Date().toISOString().slice(0,10)}
function formatDate(s){if(!s)return'';const p=s.split('-');return p.length===3?`${p[2]}.${p[1]}.${p[0]}`:s}
function fitText(text,x,y,maxW,start=52,min=20,weight=700,color='#111'){if(!text)return;ctx.save();ctx.fillStyle=color;let size=start;ctx.font=`${weight} ${size}px "Arial Narrow", Arial, sans-serif`;while(ctx.measureText(text).width>maxW&&size>min){size-=1;ctx.font=`${weight} ${size}px "Arial Narrow", Arial, sans-serif`}ctx.fillText(text,x,y);ctx.restore()}
function wrap(text,x,y,maxW,lineH,fontSize=20,maxLines=2,weight=400,color='#111'){if(!text)return;ctx.save();ctx.fillStyle=color;ctx.font=`${weight} ${fontSize}px "Arial Narrow", Arial, sans-serif`;const words=(text||'').split(/\s+/).filter(Boolean);let line='',lines=[];for(const w of words){const test=line?line+' '+w:w;if(ctx.measureText(test).width>maxW&&line){lines.push(line);line=w}else line=test}if(line)lines.push(line);lines.slice(0,maxLines).forEach((l,i)=>ctx.fillText(l,x,y+i*lineH));ctx.restore()}
function drawContainedPhoto(img,x,y,w,h,r=16){ctx.save();roundRect(x,y,w,h,r);ctx.clip();ctx.fillStyle='#ededed';ctx.fillRect(x,y,w,h);const scale=Math.min(w/img.width,h/img.height);const dw=img.width*scale,dh=img.height*scale;const dx=x+(w-dw)/2,dy=y+(h-dh)/2;ctx.drawImage(img,dx,dy,dw,dh);ctx.restore()}
function render(){if(!bg.complete)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(bg,0,0,canvas.width,canvas.height);if(photoImg)drawContainedPhoto(photoImg,42,278,445,558,18);fitText(val('lastName').toUpperCase(),525,430,420,54,28,800,'#080808');fitText(val('firstMiddleName'),525,495,420,33,21,700,'#080808');fitText(val('age'),525,570,400,27,19,700,'#111');fitText(formatDate(val('date')),785,697,172,20,16,700,'#c00000');wrap(val('place'),580,778,365,29,20,3,700,'#111');wrap(val('height'),116,950,310,22,16,1,400);wrap(val('build'),173,989,255,22,16,1,400);wrap(val('hair'),151,1028,278,22,16,2,400);wrap(val('eyes'),126,1067,302,22,16,1,400);wrap(val('special'),203,1106,226,22,16,2,400);wrap(val('jacket'),602,950,345,22,16,1,400);wrap(val('pants'),589,989,358,22,16,1,400);wrap(val('shoes'),589,1028,358,22,16,1,400);wrap(val('carrying'),627,1067,320,22,16,2,400);fitText(formatDate(val('actual')),530,1520,155,15,12,500,'#fff')}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
IDS.forEach(id=>$(id).addEventListener('input',()=>{save();render()}));$('previewBtn').onclick=render;$('clearBtn').onclick=()=>{if(confirm('Очистить все введённые данные?')){IDS.forEach(id=>$(id).value='');localStorage.removeItem('kpc-draft');photoImg=null;$('photoThumb').hidden=true;$('actual').value=new Date().toISOString().slice(0,10);render()}};
$('photo').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=ev=>{photoImg=new Image();photoImg.onload=()=>{render();$('photoThumb').src=ev.target.result;$('photoThumb').hidden=false};photoImg.src=ev.target.result};r.readAsDataURL(f)};
$('pdfBtn').onclick=()=>{render();const jpg=canvas.toDataURL('image/jpeg',.96);const win=window.open('','_blank');if(!win){$('message').textContent='Браузер заблокировал окно печати. Разрешите всплывающие окна.';return}win.document.write(`<html><head><title>Ориентировка</title><style>@page{size:A4 portrait;margin:0}html,body{margin:0;width:100%;height:100%;display:flex;align-items:center;justify-content:center;background:#fff}img{width:198mm;height:auto;max-height:297mm;display:block}</style></head><body><img src="${jpg}" onload="setTimeout(()=>window.print(),300)"></body></html>`);win.document.close();$('message').textContent='В окне печати выберите «Сохранить как PDF».'};
function net(){const on=navigator.onLine;$('netStatus').textContent=on?'Онлайн':'Офлайн — приложение работает';$('netStatus').className='badge '+(on?'online':'offline')}window.addEventListener('online',net);window.addEventListener('offline',net);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').hidden=false});$('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').hidden=true}};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));load();net();