import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js';
import {
  browserLocalPersistence, createUserWithEmailAndPassword, getAuth, GoogleAuthProvider,
  linkWithCredential, onAuthStateChanged, sendPasswordResetEmail, setPersistence, signInWithEmailAndPassword,
  signInWithPopup, signOut, updateProfile
} from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js';
import {
  addDoc, Bytes, collection, deleteDoc, doc, getDoc, getFirestore, onSnapshot,
  orderBy, query, serverTimestamp, setDoc, updateDoc
} from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
import {firebaseConfig} from './firebase-config.js';

const OWNER_EMAIL='lidiya.lynx@gmail.com';
const IDS=['lastName','firstMiddleName','age','date','place','height','build','hair','eyes','special','jacket','pants','shoes','carrying','actual'];
const $=id=>document.getElementById(id);
const canvas=$('poster'),ctx=canvas.getContext('2d');
const firebaseApp=initializeApp(firebaseConfig),auth=getAuth(firebaseApp),db=getFirestore(firebaseApp);
const googleProvider=new GoogleAuthProvider();
googleProvider.setCustomParameters({prompt:'select_account'});
let bg=new Image(),photoImg=null,deferredPrompt=null,previewOpened=false,currentCaseId=null,pendingConfirm=null;
let savedCases=[],currentUser=null,currentProfile=null,authMode='login',savingCase=false,pendingGoogleCredential=null;
let unsubscribeProfile=null,unsubscribeCases=null,unsubscribeUsers=null,posterUrls=[];
bg.src='template.jpg';
bg.onload=render;
function val(id){return $(id).value.trim()}
function save(){const d={};IDS.forEach(id=>d[id]=$(id).value);try{localStorage.setItem('kpc-draft',JSON.stringify(d))}catch{}}
function load(){try{const d=JSON.parse(localStorage.getItem('kpc-draft')||'{}');IDS.forEach(id=>{if(d[id]!=null)$(id).value=d[id]})}catch{} if(!val('actual')) $('actual').value=new Date().toISOString().slice(0,10)}
function formatDate(s){if(!s)return'';const p=s.split('-');return p.length===3?`${p[2]}.${p[1]}.${p[0]}`:s}
function fitText(text,x,y,maxW,start=52,min=20,weight=700,color='#111',family='"Arial Narrow", Arial, sans-serif'){if(!text)return;ctx.save();ctx.fillStyle=color;let size=start;ctx.font=`${weight} ${size}px ${family}`;while(ctx.measureText(text).width>maxW&&size>min){size-=1;ctx.font=`${weight} ${size}px ${family}`}ctx.fillText(text,x,y);ctx.restore()}
function wrap(text,x,y,maxW,lineH,fontSize=20,maxLines=2,weight=400,color='#111',family='"Arial Narrow", Arial, sans-serif'){if(!text)return;ctx.save();ctx.fillStyle=color;ctx.font=`${weight} ${fontSize}px ${family}`;const words=(text||'').split(/\s+/).filter(Boolean);let line='',lines=[];for(const w of words){const test=line?line+' '+w:w;if(ctx.measureText(test).width>maxW&&line){lines.push(line);line=w}else line=test}if(line)lines.push(line);lines.slice(0,maxLines).forEach((l,i)=>ctx.fillText(l,x,y+i*lineH));ctx.restore()}
function wrapBox(text,x,y,maxW,maxH,lineH=24,fontSize=20,maxLines=2,weight=400,color='#111'){if(!text)return;ctx.save();ctx.rect(x,y-20,maxW,maxH);ctx.clip();ctx.fillStyle=color;ctx.font=`${weight} ${fontSize}px "Roboto Condensed", "Arial Narrow", Arial, sans-serif`;const tokens=(text||'').split(/\s+/).filter(Boolean);const lines=[];let line='';for(const token of tokens){let word=token;while(ctx.measureText(word).width>maxW){let part='';for(const ch of word){if(ctx.measureText(part+ch).width>maxW)break;part+=ch}if(line){lines.push(line);line=''}lines.push(part);word=word.slice(part.length)}const test=line?line+' '+word:word;if(ctx.measureText(test).width>maxW&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line);const visible=lines.slice(0,Math.min(maxLines,Math.floor(maxH/lineH)));visible.forEach((l,i)=>{let out=l;if(i===visible.length-1&&lines.length>visible.length){while(ctx.measureText(out+'…').width>maxW&&out.length>1)out=out.slice(0,-1);out+='…'}ctx.fillText(out,x,y+i*lineH)});ctx.restore()}
function drawCoverPhoto(img,x,y,w,h,r=16){ctx.save();roundRect(x,y,w,h,r);ctx.clip();const scale=Math.max(w/img.width,h/img.height);const dw=img.width*scale,dh=img.height*scale;const dx=x+(w-dw)/2,dy=dh>h?y+(h-dh)*0.12:y+(h-dh)/2;ctx.drawImage(img,dx,dy,dw,dh);ctx.restore()}
function render(){if(!bg.complete)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(bg,0,0,canvas.width,canvas.height);if(photoImg)drawCoverPhoto(photoImg,42,278,445,558,18);fitText(val('lastName').toUpperCase(),525,430,420,62,34,600,'#080808','Oswald, "Arial Narrow", Arial, sans-serif');fitText(val('firstMiddleName'),525,497,420,45,26,600,'#080808','Oswald, "Arial Narrow", Arial, sans-serif');fitText(val('age'),525,552,360,28,20,500,'#111','"Roboto Condensed", "Arial Narrow", Arial, sans-serif');fitText(formatDate(val('date')),785,690,172,23,18,500,'#c00000','"Roboto Condensed", "Arial Narrow", Arial, sans-serif');wrap(val('place'),580,792,365,32,27,3,500,'#111','"Roboto Condensed", "Arial Narrow", Arial, sans-serif');wrapBox(val('height'),130,953,177,39,24,20,1,400);wrapBox(val('build'),224,992,231,52,24,20,2,400);wrapBox(val('hair'),158,1028,306,52,24,20,2,400);wrapBox(val('eyes'),148,1065,269,39,24,20,1,400);wrapBox(val('special'),244,1104,210,68,23,20,3,400);wrapBox(val('jacket'),623,953,369,60,24,20,2,400);wrapBox(val('pants'),623,992,374,39,24,20,1,400);wrapBox(val('shoes'),623,1034,369,39,24,20,1,400);wrapBox(val('carrying'),644,1075,357,58,24,20,2,400);fitText(formatDate(val('actual')),530,1521,155,20,15,500,'#fff','"Roboto Condensed", "Arial Narrow", Arial, sans-serif')}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function renderPreservingFocus(el){const start=el.selectionStart,end=el.selectionEnd;save();if(previewOpened)render();requestAnimationFrame(()=>{if(!el||!el.isConnected)return;if(document.activeElement!==el)el.focus({preventScroll:true});if(start!=null&&el.setSelectionRange)el.setSelectionRange(start,end)})}
function openPreview(){const wasOpened=previewOpened;previewOpened=true;$('previewCard').hidden=false;$('layout').classList.add('preview-open');$('previewBtn').textContent='Обновить предпросмотр';render();if(!wasOpened&&window.matchMedia('(max-width:900px)').matches)$('previewCard').scrollIntoView({block:'start',behavior:'smooth'})}
function closePreview(){previewOpened=false;$('previewCard').hidden=true;$('layout').classList.remove('preview-open');$('previewBtn').textContent='Открыть предпросмотр'}
function formData(){const data={};IDS.forEach(id=>data[id]=$(id).value);return data}
function makeCaseTitle(data){const name=[data.lastName.trim(),data.firstMiddleName.trim()].filter(Boolean).join(' ');return `${name}, ${data.age.trim()}`}
function resetForm(){IDS.forEach(id=>$(id).value='');localStorage.removeItem('kpc-draft');photoImg=null;$('photo').value='';$('photoThumb').src='';$('photoThumb').hidden=true;$('actual').value=new Date().toISOString().slice(0,10);closePreview()}
function closeMenu(){$('mainMenu').hidden=true;$('menuBtn').setAttribute('aria-expanded','false');$('menuBtn').setAttribute('aria-label','Открыть главное меню')}
function toggleMenu(){const willOpen=$('mainMenu').hidden;$('mainMenu').hidden=!willOpen;$('menuBtn').setAttribute('aria-expanded',String(willOpen));$('menuBtn').setAttribute('aria-label',willOpen?'Закрыть главное меню':'Открыть главное меню')}
function menuList(containerId,countId,status,type){const container=$(containerId);const items=savedCases.filter(item=>item.status===status&&item.type===type).sort((a,b)=>b.createdAt-a.createdAt);container.replaceChildren();$(countId).textContent=String(items.length);if(!items.length){const empty=document.createElement('div');empty.className='empty-link';empty.textContent='Нет ориентировок';container.append(empty);return}items.forEach(item=>{const button=document.createElement('button');button.type='button';button.className='case-link'+(item.id===currentCaseId?' current':'');button.textContent=item.title;button.onclick=()=>openCase(item.id,true);container.append(button)})}
function renderMenu(){menuList('activePss','activePssCount','active','ПСС');menuList('activePtp','activePtpCount','active','ПТП');menuList('archivePss','archivePssCount','archive','ПСС');menuList('archivePtp','archivePtpCount','archive','ПТП')}
function showCreation(updateHistory=false){currentCaseId=null;$('layout').hidden=false;$('caseView').hidden=true;$('pageSubtitle').textContent='Создание ориентировки';if(updateHistory)history.pushState(null,'',location.pathname+location.search);renderMenu();closeMenu()}
function openCase(id,updateHistory=false){const item=savedCases.find(entry=>entry.id===id);if(!item){showCreation(updateHistory);return}currentCaseId=id;$('layout').hidden=true;$('caseView').hidden=false;$('caseTitle').textContent=item.title;$('caseMeta').textContent=`${item.type} · ${item.status==='active'?'Активный поиск':'Архив'}`;$('caseStatus').textContent=item.status==='active'?'Активный поиск':'В архиве';$('caseStatus').className='case-status'+(item.status==='archive'?' archive':'');$('savedPoster').src=item.poster;$('caseActions').hidden=item.status!=='active';$('pageSubtitle').textContent=item.title;if(updateHistory)history.pushState(null,'',`#case=${encodeURIComponent(id)}`);renderMenu();closeMenu();window.scrollTo({top:0,behavior:'smooth'})}
function route(){const params=new URLSearchParams(location.hash.slice(1));const id=params.get('case');if(id&&savedCases.some(item=>item.id===id))openCase(id);else showCreation()}
function validateSavedCase(){const fields=[['lastName','фамилию'],['firstMiddleName','имя и отчество'],['age','возраст']];for(const [id,label] of fields){if(!val(id)){$('message').textContent=`Чтобы создать запись, укажите ${label}.`;$(id).focus();return false}}if(!bg.complete||!bg.naturalWidth){$('message').textContent='Шаблон ориентировки ещё загружается. Повторите через несколько секунд.';return false}return true}
function openSearchTypeDialog(){if(!validateSavedCase())return;$('message').textContent='';$('searchTypeDialog').showModal()}
function canvasBlob(quality){return new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',quality))}
async function posterBytes(){for(const quality of [.82,.72,.62,.52,.44]){const blob=await canvasBlob(quality);if(blob&&blob.size<=768000)return new Uint8Array(await blob.arrayBuffer())}throw new Error('poster-too-large')}
async function createSavedCase(type){if(savingCase)return;savingCase=true;$('message').textContent='Сохраняю ориентировку…';try{render();const data=formData(),title=makeCaseTitle(data),bytes=await posterBytes();const ref=await addDoc(collection(db,'cases'),{type,status:'active',title,data,poster:Bytes.fromUint8Array(bytes),createdAt:serverTimestamp(),createdBy:currentUser.uid,createdByEmail:currentUser.email||''});resetForm();const poster=URL.createObjectURL(new Blob([bytes],{type:'image/jpeg'}));posterUrls.push(poster);savedCases=[{id:ref.id,type,status:'active',title,data,poster,createdAt:Date.now()},...savedCases.filter(item=>item.id!==ref.id)];openCase(ref.id,true)}catch(error){console.error(error);$('message').textContent=error.message==='poster-too-large'?'Ориентировка получилась слишком большой. Попробуйте загрузить фото меньшего размера.':'Не удалось сохранить ориентировку. Проверьте интернет и повторите.'}finally{savingCase=false}}
function askConfirmation({title,text,label,kind='danger',action}){$('confirmTitle').textContent=title;$('confirmText').textContent=text;$('confirmAcceptBtn').textContent=label;$('confirmAcceptBtn').className=kind;pendingConfirm=action;$('confirmDialog').showModal()}
function deleteCurrentCase(){const item=savedCases.find(entry=>entry.id===currentCaseId);if(!item)return;askConfirmation({title:'Удалить ориентировку?',text:`Запись «${item.title}» будет удалена без возможности восстановления.`,label:'Удалить',action:async()=>{try{await deleteDoc(doc(db,'cases',item.id));showCreation(true)}catch(error){console.error(error);$('message').textContent='Не удалось удалить ориентировку.'}}})}
function archiveCurrentCase(){const item=savedCases.find(entry=>entry.id===currentCaseId);if(!item)return;askConfirmation({title:'Убрать ориентировку в архив?',text:`Запись «${item.title}» переместится в Архив → ${item.type}.`,label:'Убрать в архив',kind:'primary',action:async()=>{try{await updateDoc(doc(db,'cases',item.id),{status:'archive',archivedAt:serverTimestamp(),archivedBy:currentUser.uid});const groups=document.querySelectorAll('.menu-group');if(groups.length>1)groups[1].open=true}catch(error){console.error(error);$('message').textContent='Не удалось перенести ориентировку в архив.'}}})}

function authErrorText(error){const messages={'auth/email-already-in-use':'Этот email уже зарегистрирован. Войдите существующим способом.','auth/account-exists-with-different-credential':'Этот email уже зарегистрирован другим способом.','auth/invalid-credential':'Неверный email или пароль.','auth/invalid-email':'Проверьте написание email.','auth/weak-password':'Пароль должен содержать не менее 6 символов.','auth/popup-closed-by-user':'Окно входа было закрыто.','auth/popup-blocked':'Браузер заблокировал окно входа. Разрешите всплывающие окна.','auth/unauthorized-domain':'Этот адрес сайта еще не разрешен в настройках Firebase.','auth/too-many-requests':'Слишком много попыток. Подождите несколько минут.'};return messages[error.code]||'Не удалось выполнить вход. Проверьте интернет и повторите.'}
function setAuthMode(mode){authMode=mode;document.querySelectorAll('[data-auth-mode]').forEach(button=>button.classList.toggle('active',button.dataset.authMode===mode));$('authTitle').textContent=mode==='login'?'Вход':'Регистрация';$('authLead').textContent=mode==='login'?'Войдите, чтобы работать с общими ориентировками.':'Создайте учетную запись. Доступ подтвердит администратор.';$('emailAuthBtn').textContent=mode==='login'?'Войти':'Зарегистрироваться';$('resetPasswordBtn').hidden=mode!=='login';$('authPassword').autocomplete=mode==='login'?'current-password':'new-password';$('authMessage').textContent=''}
function showSignedOut(){document.body.className='auth-signed-out';$('authGate').hidden=false;$('authPanel').hidden=false;$('pendingPanel').hidden=true;$('userTools').hidden=true;setAuthMode('login')}
function showPending(user){document.body.className='auth-pending';$('authGate').hidden=false;$('authPanel').hidden=true;$('pendingPanel').hidden=false;$('pendingName').textContent=user.displayName||'Новый пользователь';$('pendingEmail').textContent=user.email||'';$('pendingMessage').textContent=''}
function showReady(user,profile){document.body.className='auth-ready';$('authGate').hidden=true;$('userTools').hidden=false;$('currentUserName').textContent=user.displayName||user.email||'Пользователь';$('manageUsersBtn').hidden=profile.role!=='admin';subscribeCases();if(profile.role==='admin')subscribeUsers();else stopUsersSubscription()}
async function ensureProfile(user){const ref=doc(db,'users',user.uid),snapshot=await getDoc(ref);if(!snapshot.exists()){const isOwner=(user.email||'').toLowerCase()===OWNER_EMAIL;await setDoc(ref,{email:user.email||'',displayName:user.displayName||(user.email||'').split('@')[0],approved:isOwner,role:isOwner?'admin':'member',createdAt:serverTimestamp()})}return ref}
function stopCaseSubscription(){if(unsubscribeCases){unsubscribeCases();unsubscribeCases=null}posterUrls.forEach(URL.revokeObjectURL);posterUrls=[];savedCases=[];renderMenu()}
function stopUsersSubscription(){if(unsubscribeUsers){unsubscribeUsers();unsubscribeUsers=null}$('pendingUsersCount').hidden=true}
function subscribeCases(){if(unsubscribeCases)return;unsubscribeCases=onSnapshot(query(collection(db,'cases'),orderBy('createdAt','desc')),snapshot=>{posterUrls.forEach(URL.revokeObjectURL);posterUrls=[];savedCases=snapshot.docs.map(entry=>{const data=entry.data();const bytes=data.poster?.toUint8Array?.();const poster=bytes?URL.createObjectURL(new Blob([bytes],{type:'image/jpeg'})):'';if(poster)posterUrls.push(poster);return{id:entry.id,...data,poster,createdAt:data.createdAt?.toMillis?.()||0}});renderMenu();if(currentCaseId){if(savedCases.some(item=>item.id===currentCaseId))openCase(currentCaseId);else showCreation(true)}else route()},error=>{console.error(error);$('message').textContent='Не удалось загрузить общие ориентировки.'})}
function subscribeUsers(){if(unsubscribeUsers)return;unsubscribeUsers=onSnapshot(collection(db,'users'),snapshot=>{const users=snapshot.docs.map(entry=>({id:entry.id,...entry.data()})).sort((a,b)=>Number(a.approved)-Number(b.approved)||String(a.displayName).localeCompare(String(b.displayName),'ru'));renderUsers(users);const pending=users.filter(user=>!user.approved).length;$('pendingUsersCount').textContent=String(pending);$('pendingUsersCount').hidden=pending===0},error=>console.error(error))}
function renderUsers(users){const list=$('usersList');list.replaceChildren();if(!users.length){list.textContent='Зарегистрированных пользователей пока нет.';return}users.forEach(user=>{const row=document.createElement('div');row.className='user-row';const info=document.createElement('div');info.className='user-info';const name=document.createElement('strong');name.textContent=user.displayName||'Без имени';const email=document.createElement('span');email.textContent=user.email||'';info.append(name,email);const state=document.createElement('div');state.className='user-state';const badge=document.createElement('span');badge.className='approval '+(user.approved?'approved':'pending');badge.textContent=user.role==='admin'?'Администратор':user.approved?'Доступ открыт':'Ожидает';state.append(badge);if(user.role!=='admin'){const button=document.createElement('button');button.type='button';button.className=user.approved?'ghost small':'primary small';button.textContent=user.approved?'Закрыть доступ':'Подтвердить';button.onclick=async()=>{button.disabled=true;try{await updateDoc(doc(db,'users',user.id),{approved:!user.approved})}catch(error){console.error(error);button.disabled=false}};state.append(button)}row.append(info,state);list.append(row)})}
async function handleAuthenticatedUser(user){currentUser=user;try{const ref=await ensureProfile(user);if(unsubscribeProfile)unsubscribeProfile();unsubscribeProfile=onSnapshot(ref,snapshot=>{currentProfile=snapshot.data();if(currentProfile?.approved)showReady(user,currentProfile);else{stopCaseSubscription();stopUsersSubscription();showPending(user)}},error=>{console.error(error);showPending(user);$('pendingMessage').textContent='Не удалось проверить доступ. Обновите страницу.'})}catch(error){console.error(error);showPending(user);$('pendingMessage').textContent='Не удалось завершить регистрацию. Обновите страницу.'}}
async function logout(){if(unsubscribeProfile){unsubscribeProfile();unsubscribeProfile=null}stopCaseSubscription();stopUsersSubscription();currentUser=null;currentProfile=null;await signOut(auth)}

IDS.forEach(id=>{const el=$(id);el.addEventListener('input',()=>renderPreservingFocus(el));el.addEventListener('keydown',e=>{if(e.key==='Enter'&&el.tagName!=='TEXTAREA')e.preventDefault()})});$('previewBtn').onclick=openPreview;$('saveCaseBtn').onclick=openSearchTypeDialog;$('clearBtn').onclick=()=>{if(confirm('Очистить все введённые данные?'))resetForm()};
$('menuBtn').onclick=toggleMenu;$('createViewBtn').onclick=()=>showCreation(true);document.addEventListener('click',event=>{if(!$('menuWrap').contains(event.target))closeMenu()});
document.querySelectorAll('[data-search-type]').forEach(button=>button.onclick=()=>{$('searchTypeDialog').close();createSavedCase(button.dataset.searchType)});
$('confirmCancelBtn').onclick=()=>{$('confirmDialog').close();pendingConfirm=null};$('confirmAcceptBtn').onclick=()=>{const action=pendingConfirm;pendingConfirm=null;$('confirmDialog').close();if(action)action()};
$('deleteCaseBtn').onclick=deleteCurrentCase;$('archiveCaseBtn').onclick=archiveCurrentCase;window.addEventListener('popstate',route);
$('logoutBtn').onclick=logout;$('pendingLogoutBtn').onclick=logout;$('pendingRefreshBtn').onclick=async()=>{if(!currentUser)return;$('pendingMessage').textContent='Проверяю…';try{const snapshot=await getDoc(doc(db,'users',currentUser.uid));$('pendingMessage').textContent=snapshot.data()?.approved?'Доступ открыт. Загружаю данные…':'Подтверждения пока нет.'}catch{$('pendingMessage').textContent='Не удалось проверить доступ.'}};
$('manageUsersBtn').onclick=()=>{$('usersDialog').showModal()};$('closeUsersBtn').onclick=()=>{$('usersDialog').close()};
document.querySelectorAll('[data-auth-mode]').forEach(button=>button.onclick=()=>setAuthMode(button.dataset.authMode));
$('googleAuthBtn').onclick=async()=>{$('authMessage').textContent='Открываю вход через Google…';try{await signInWithPopup(auth,googleProvider)}catch(error){console.error(error);if(error.code==='auth/account-exists-with-different-credential'){pendingGoogleCredential=GoogleAuthProvider.credentialFromError(error);setAuthMode('login');$('authEmail').value=error.customData?.email||'';$('authMessage').textContent='Этот email уже зарегистрирован. Введите пароль: после входа Google будет подключен к той же учетной записи.'}else $('authMessage').textContent=authErrorText(error)}};
$('emailAuthForm').onsubmit=async event=>{event.preventDefault();const email=$('authEmail').value.trim(),password=$('authPassword').value;$('emailAuthBtn').disabled=true;$('authMessage').textContent=authMode==='login'?'Выполняю вход…':'Создаю учетную запись…';try{if(authMode==='login'){const credential=await signInWithEmailAndPassword(auth,email,password);if(pendingGoogleCredential){await linkWithCredential(credential.user,pendingGoogleCredential);pendingGoogleCredential=null}}else{const credential=await createUserWithEmailAndPassword(auth,email,password);await updateProfile(credential.user,{displayName:email.split('@')[0]})}}catch(error){console.error(error);$('authMessage').textContent=authErrorText(error)}finally{$('emailAuthBtn').disabled=false}};
$('resetPasswordBtn').onclick=async()=>{const email=$('authEmail').value.trim();if(!email){$('authMessage').textContent='Сначала укажите email.';$('authEmail').focus();return}try{await sendPasswordResetEmail(auth,email);$('authMessage').textContent='Письмо для восстановления пароля отправлено.'}catch(error){console.error(error);$('authMessage').textContent=authErrorText(error)}};
$('photo').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=ev=>{photoImg=new Image();photoImg.onload=()=>{render();$('photoThumb').src=ev.target.result;$('photoThumb').hidden=false};photoImg.src=ev.target.result};r.readAsDataURL(f)};
$('pdfBtn').onclick=()=>{render();const jpg=canvas.toDataURL('image/jpeg',.96);const win=window.open('','_blank');if(!win){$('message').textContent='Браузер заблокировал окно печати. Разрешите всплывающие окна.';return}win.document.write(`<html><head><title>Ориентировка</title><style>@page{size:A4 portrait;margin:0}html,body{margin:0;width:100%;height:100%;display:flex;align-items:center;justify-content:center;background:#fff}img{width:198mm;height:auto;max-height:297mm;display:block}</style></head><body><img src="${jpg}" onload="setTimeout(()=>window.print(),300)"></body></html>`);win.document.close();$('message').textContent='В окне печати выберите «Сохранить как PDF».'};
function net(){const on=navigator.onLine;$('netStatus').textContent=on?'Онлайн':'Офлайн';$('netStatus').className='badge '+(on?'online':'offline')}window.addEventListener('online',net);window.addEventListener('offline',net);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').hidden=false});$('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').hidden=true}};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));if(document.fonts)document.fonts.ready.then(render);load();renderMenu();net();setPersistence(auth,browserLocalPersistence).catch(console.error);onAuthStateChanged(auth,user=>{if(user)handleAuthenticatedUser(user);else{if(unsubscribeProfile){unsubscribeProfile();unsubscribeProfile=null}stopCaseSubscription();stopUsersSubscription();currentUser=null;currentProfile=null;showSignedOut()}});
