import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js';
import {
  browserLocalPersistence, createUserWithEmailAndPassword, EmailAuthProvider, getAuth, GoogleAuthProvider,
  linkWithCredential, linkWithPopup, onAuthStateChanged, sendPasswordResetEmail,
  setPersistence, signInWithEmailAndPassword, signInWithPopup, signOut, updatePassword, updateProfile
} from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js';
import {
  Bytes, collection, deleteDoc, deleteField, doc, getDoc, getDocFromServer, getFirestore,
  onSnapshot, orderBy, query, serverTimestamp, setDoc, updateDoc, where
} from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
import {firebaseConfig} from './firebase-config.js';

const OWNER_EMAIL='lidiya.lynx@gmail.com';
const ARCHIVE_UPLOAD_URL='https://script.google.com/macros/s/AKfycbyF6IIZKnySKLSn6L7Fnf-lmd7vQ8Z5z8IFSRg8TixVVLK6-SpxSRsoyKrvrlxKXGBcZw/exec';
const IDS=['lastName','firstMiddleName','age','date','place','height','build','hair','eyes','special','jacket','pants','shoes','carrying','actual'];
const $=id=>document.getElementById(id);
const canvas=$('poster'),ctx=canvas.getContext('2d');
const firebaseApp=initializeApp(firebaseConfig),auth=getAuth(firebaseApp),db=getFirestore(firebaseApp);
const googleProvider=new GoogleAuthProvider();
googleProvider.setCustomParameters({prompt:'select_account'});
let bg=new Image(),photoImg=null,deferredPrompt=null,previewOpened=false,currentCaseId=null,currentView='home',pendingConfirm=null;
let savedCases=[],currentUser=null,currentProfile=null,authMode='login',savingCase=false,pendingGoogleCredential=null;
let unsubscribeProfile=null,unsubscribeCases=null,unsubscribeUsers=null,posterUrls=[];
let userProfiles=new Map(),profilePhotoUrls=[],currentProfilePhotoUrl=null,usersSubscriptionMode=null;
let pendingCaseWrite=null;
let unsubscribeNotes=null,notesCaseId=null,savedNotes=[],noteUrls=[];
let editingNoteId=null,noteImageAttachment=null,savingNote=false;
let archivingCase=false;
let notesReady=false;
let unsubscribeTracks=null,tracksCaseId=null,savedTracks=[],tracksReady=false,uploadingTracks=false;
const THEME_KEY='kpc-theme';
const TRACK_EXTENSIONS=new Set(['gpx','gpx.bin','kml','kmz','tcx','fit']);
const MAX_TRACK_FILE_BYTES=15*1024*1024;
const MAX_TRACK_FILES=10;
const SHARED_TRACKS_CACHE='kpc-shared-tracks-v1';
let sharedTracksBatch=new URLSearchParams(location.search).get('sharedTracks')||'',sharedTracksMetadata=[],sharedTracksFiles=[],sharedTracksOpened=false;
bg.src='template.jpg';
bg.onload=render;
function val(id){return $(id).value.trim()}
function save(){const d={};IDS.forEach(id=>d[id]=$(id).value);try{localStorage.setItem('kpc-draft',JSON.stringify(d))}catch{}}
function load(){try{const d=JSON.parse(localStorage.getItem('kpc-draft')||'{}');IDS.forEach(id=>{if(d[id]!=null)$(id).value=d[id]})}catch{} if(!val('actual')) $('actual').value=new Date().toISOString().slice(0,10)}
function formatDate(s){if(!s)return'';const p=s.split('-');return p.length===3?`${p[2]}.${p[1]}.${p[0]}`:s}
function fitText(text,x,y,maxW,start=52,min=20,weight=700,color='#111',family='"Arial Narrow", Arial, sans-serif'){if(!text)return;ctx.save();ctx.fillStyle=color;let size=start;ctx.font=`${weight} ${size}px ${family}`;while(ctx.measureText(text).width>maxW&&size>min){size-=1;ctx.font=`${weight} ${size}px ${family}`}ctx.fillText(text,x,y);ctx.restore()}
function wrap(text,x,y,maxW,lineH,fontSize=20,maxLines=2,weight=400,color='#111',family='"Arial Narrow", Arial, sans-serif'){if(!text)return;ctx.save();ctx.fillStyle=color;ctx.font=`${weight} ${fontSize}px ${family}`;const words=(text||'').split(/\s+/).filter(Boolean);let line='',lines=[];for(const w of words){const test=line?line+' '+w:w;if(ctx.measureText(test).width>maxW&&line){lines.push(line);line=w}else line=test}if(line)lines.push(line);lines.slice(0,maxLines).forEach((l,i)=>ctx.fillText(l,x,y+i*lineH));ctx.restore()}
function wrapBox(text,x,y,maxW,maxH,lineH=24,fontSize=20,maxLines=2,weight=400,color='#111'){if(!text)return;ctx.save();ctx.rect(x,y-20,maxW,maxH);ctx.clip();ctx.fillStyle=color;ctx.font=`${weight} ${fontSize}px "Roboto Condensed", "Arial Narrow", Arial, sans-serif`;const tokens=(text||'').split(/\s+/).filter(Boolean);const lines=[];let line='';for(const token of tokens){let word=token;while(ctx.measureText(word).width>maxW){let part='';for(const ch of word){if(ctx.measureText(part+ch).width>maxW)break;part+=ch}if(line){lines.push(line);line=''}lines.push(part);word=word.slice(part.length)}const test=line?line+' '+word:word;if(ctx.measureText(test).width>maxW&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line);const visible=lines.slice(0,Math.min(maxLines,Math.floor(maxH/lineH)));visible.forEach((l,i)=>{let out=l;if(i===visible.length-1&&lines.length>visible.length){while(ctx.measureText(out+'…').width>maxW&&out.length>1)out=out.slice(0,-1);out+='…'}ctx.fillText(out,x,y+i*lineH)});ctx.restore()}
function drawCoverPhoto(img,x,y,w,h,r=16){ctx.save();roundRect(x,y,w,h,r);ctx.clip();const scale=Math.max(w/img.width,h/img.height);const dw=img.width*scale,dh=img.height*scale;const dx=x+(w-dw)/2,dy=dh>h?y+(h-dh)*0.12:y+(h-dh)/2;ctx.drawImage(img,dx,dy,dw,dh);ctx.restore()}
function render(){if(!bg.complete)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(bg,0,0,canvas.width,canvas.height);if(photoImg)drawCoverPhoto(photoImg,42,278,445,558,18);fitText(val('lastName').toUpperCase(),525,430,420,62,34,600,'#080808','Oswald, "Arial Narrow", Arial, sans-serif');fitText(val('firstMiddleName'),525,497,420,45,26,600,'#080808','Oswald, "Arial Narrow", Arial, sans-serif');fitText(val('age'),525,552,360,28,20,500,'#111','"Roboto Condensed", "Arial Narrow", Arial, sans-serif');fitText(formatDate(val('date')),785,690,172,23,18,500,'#c00000','"Roboto Condensed", "Arial Narrow", Arial, sans-serif');wrap(val('place'),580,792,365,32,27,3,500,'#111','"Roboto Condensed", "Arial Narrow", Arial, sans-serif');wrapBox(val('height'),130,953,177,39,24,20,1,400);wrapBox(val('build'),224,992,231,52,24,20,2,400);wrapBox(val('hair'),158,1028,306,52,24,20,2,400);wrapBox(val('eyes'),148,1065,269,39,24,20,1,400);wrapBox(val('special'),244,1104,210,68,23,20,3,400);wrapBox(val('jacket'),623,953,369,60,24,20,2,400);wrapBox(val('pants'),623,992,374,39,24,20,1,400);wrapBox(val('shoes'),623,1034,369,39,24,20,1,400);wrapBox(val('carrying'),644,1075,357,58,24,20,2,400);fitText(formatDate(val('actual')),530,1521,155,20,15,500,'#fff','"Roboto Condensed", "Arial Narrow", Arial, sans-serif')}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function renderPreservingFocus(el){const start=el.selectionStart,end=el.selectionEnd;save();if(previewOpened)render();requestAnimationFrame(()=>{if(!el||!el.isConnected)return;if(document.activeElement!==el)el.focus({preventScroll:true});if(start!=null&&el.setSelectionRange)el.setSelectionRange(start,end)})}
function openPreview(){const wasOpened=previewOpened;previewOpened=true;$('previewCard').hidden=false;$('layout').classList.add('preview-open');$('previewBtn').textContent='Обновить предпросмотр';render();if(!wasOpened&&window.matchMedia('(max-width:900px)').matches)$('previewCard').scrollIntoView({block:'start',behavior:'smooth'})}
function closePreview(){previewOpened=false;$('previewCard').hidden=true;$('layout').classList.remove('preview-open');$('previewBtn').textContent='Открыть предпросмотр'}
function formData(){const data={};IDS.forEach(id=>data[id]=$(id).value);return data}
function makeCaseTitle(data){const name=[data.lastName.trim(),data.firstMiddleName.trim()].filter(Boolean).join(' ');return `${name}, ${data.age.trim()}`}
function resetForm(){IDS.forEach(id=>$(id).value='');localStorage.removeItem('kpc-draft');photoImg=null;$('photo').value='';$('photoThumb').src='';$('photoThumb').hidden=true;$('actual').value=new Date().toISOString().slice(0,10);$('message').textContent='';closePreview()}
function closeMenu(){$('mainMenu').hidden=true;$('menuBtn').setAttribute('aria-expanded','false');$('menuBtn').setAttribute('aria-label','Открыть главное меню')}
function toggleMenu(){const willOpen=$('mainMenu').hidden;$('mainMenu').hidden=!willOpen;$('menuBtn').setAttribute('aria-expanded',String(willOpen));$('menuBtn').setAttribute('aria-label',willOpen?'Закрыть главное меню':'Открыть главное меню')}
function currentIsAdmin(){return currentProfile?.approved===true&&currentProfile?.role==='admin'}
function currentIsOwner(){return currentIsAdmin()&&(currentUser?.email||'').toLowerCase()===OWNER_EMAIL}
function homeCaseDate(item){const timestamp=item.archivedAtMs||item.createdAt;if(!timestamp)return'Дата не указана';return new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'short',year:'numeric'}).format(timestamp)}
function homeCaseControl(item){const archived=item.status==='archive',driveArchive=archived&&item.archiveUrl,control=document.createElement(driveArchive?'a':'button');control.className='home-case-row'+(archived?' is-archive':'');if(driveArchive){control.href=item.archiveUrl;control.target='_blank';control.rel='noopener'}else{control.type='button';control.onclick=()=>openCase(item.id,true)}const text=document.createElement('span'),titleLine=document.createElement('span'),title=document.createElement('strong'),meta=document.createElement('small'),arrow=document.createElement('span');titleLine.className='home-case-title';title.textContent=item.title||'Без названия';titleLine.append(title);if(archived){const status=document.createElement('span');status.className='home-case-status';status.textContent='Архив';titleLine.append(status)}meta.textContent=`${item.type} · ${archived?'Завершен':'Активный поиск'} · ${homeCaseDate(item)}`;arrow.className='home-case-arrow';arrow.textContent=driveArchive?'↗':'→';arrow.setAttribute('aria-hidden','true');text.append(titleLine,meta);control.append(text,arrow);return control}
function renderHomeList(containerId,type,status='active'){const container=$(containerId),items=savedCases.filter(item=>item.status===status&&item.type===type).sort((a,b)=>Math.max(b.archivedAtMs||0,b.createdAt||0)-Math.max(a.archivedAtMs||0,a.createdAt||0)).slice(0,status==='archive'?6:4);container.replaceChildren();if(!items.length){const empty=document.createElement('div');empty.className='home-empty';empty.textContent=status==='archive'?`Архивных ориентировок ${type} пока нет`:`Активных поисков ${type} сейчас нет`;container.append(empty);return}items.forEach(item=>container.append(homeCaseControl(item)))}
function renderHome(){if(!$('homeView'))return;const activePss=savedCases.filter(item=>item.status==='active'&&item.type==='ПСС').length,activePtp=savedCases.filter(item=>item.status==='active'&&item.type==='ПТП').length,archive=savedCases.filter(item=>item.status==='archive').length;$('homeActivePssCount').textContent=String(activePss);$('homeActivePtpCount').textContent=String(activePtp);$('homeArchiveCount').textContent=String(archive);$('homeTotalCount').textContent=String(savedCases.length);$('homeUserName').textContent=currentProfile?.displayName||currentUser?.displayName||currentUser?.email||'пользователь';$('homeUserRole').textContent=currentProfile?profileRoleLabel():'';$('homeCreateCaseBtn').hidden=!currentIsAdmin();renderHomeList('homeActivePss','ПСС');renderHomeList('homeActivePtp','ПТП');renderHomeList('homeArchivePss','ПСС','archive');renderHomeList('homeArchivePtp','ПТП','archive');const recent=[...savedCases].sort((a,b)=>Math.max(b.archivedAtMs||0,b.createdAt||0)-Math.max(a.archivedAtMs||0,a.createdAt||0)).slice(0,6),container=$('homeRecentCases');container.replaceChildren();if(!recent.length){const empty=document.createElement('div');empty.className='home-empty';empty.textContent='Ориентировок пока нет';container.append(empty)}else recent.forEach(item=>container.append(homeCaseControl(item)))}
function toggleHomeSection(status,type='',forceOpen=false){const section=$(status==='archive'?'homeArchiveSection':'homeActiveSection'),button=$(status==='archive'?'homeArchiveBtn':'homeActiveBtn'),willOpen=forceOpen||section.hidden;if(!willOpen&&type)return;section.hidden=!willOpen;button.classList.toggle('expanded',willOpen);button.setAttribute('aria-expanded',String(willOpen));if(willOpen){const groups=section.querySelectorAll('.home-search-group');groups.forEach(group=>group.classList.remove('home-focus'));if(type){const target=section.querySelector(`.home-search-group:${type==='ПТП'?'last':'first'}-child`);target?.classList.add('home-focus')}section.scrollIntoView({behavior:'smooth',block:'start'})}}
function menuList(containerId,countId,status,type){const container=$(containerId);const items=savedCases.filter(item=>item.status===status&&item.type===type).sort((a,b)=>b.createdAt-a.createdAt);container.replaceChildren();$(countId).textContent=String(items.length);if(!items.length){const empty=document.createElement('div');empty.className='empty-link';empty.textContent='Нет ориентировок';container.append(empty);return}items.forEach(item=>{const isDriveArchive=item.status==='archive'&&item.archiveUrl,control=document.createElement(isDriveArchive?'a':'button'),isCurrent=!isDriveArchive&&item.id===currentCaseId;if(isDriveArchive){control.href=item.archiveUrl;control.target='_blank';control.rel='noopener';control.className='case-link archive-drive-link';control.setAttribute('aria-label',`Открыть «${item.title}» на Google Drive`)}else{control.type='button';control.className='case-link'+(isCurrent?' current':'');if(isCurrent)control.setAttribute('aria-current','page');control.onclick=()=>openCase(item.id,true)}control.textContent=item.title;container.append(control)})}
function updateMenuLocation(item){const home=currentView==='home',creation=currentView==='creation';$('homeViewBtn').classList.toggle('current',home);$('createViewBtn').classList.toggle('current',creation);if(home)$('homeViewBtn').setAttribute('aria-current','page');else $('homeViewBtn').removeAttribute('aria-current');if(creation)$('createViewBtn').setAttribute('aria-current','page');else $('createViewBtn').removeAttribute('aria-current');document.querySelectorAll('.menu-group').forEach(group=>{const groupCurrent=currentView==='case'&&!!item&&group.dataset.status===item.status;group.classList.toggle('current',groupCurrent);if(groupCurrent)group.open=true;group.querySelectorAll('.menu-subgroup').forEach(subgroup=>subgroup.classList.toggle('current',groupCurrent&&subgroup.dataset.type===item.type))})}
function renderMenu(){menuList('activePss','activePssCount','active','ПСС');menuList('activePtp','activePtpCount','active','ПТП');menuList('archivePss','archivePssCount','archive','ПСС');menuList('archivePtp','archivePtpCount','archive','ПТП');updateMenuLocation(savedCases.find(item=>item.id===currentCaseId)||null);renderHome()}
function showHome(updateHistory=false){stopNotesSubscription();stopTracksSubscription();currentCaseId=null;currentView='home';$('homeView').hidden=false;$('layout').hidden=true;$('caseView').hidden=true;$('pageSubtitle').textContent='Главная';if(updateHistory)history.pushState(null,'','#view=home');renderMenu();closeMenu();window.scrollTo({top:0,behavior:'smooth'})}
function showCreation(updateHistory=false){stopNotesSubscription();stopTracksSubscription();currentCaseId=null;currentView='creation';$('homeView').hidden=true;$('layout').hidden=false;$('caseView').hidden=true;$('pageSubtitle').textContent='Создание ориентировки';if(updateHistory)history.pushState(null,'','#view=create');renderMenu();closeMenu()}
function openCase(id,updateHistory=false){const item=savedCases.find(entry=>entry.id===id);if(!item){showHome(updateHistory);return}if(item.status==='archive'&&item.archiveUrl){window.open(item.archiveUrl,'_blank','noopener');return}currentCaseId=id;currentView='case';$('homeView').hidden=true;$('layout').hidden=true;$('caseView').hidden=false;$('caseTitle').textContent=item.title;$('caseMeta').textContent=`${item.type} · ${item.status==='active'?'Активный поиск':'Архив'}`;$('caseStatus').textContent=item.status==='active'?'Активный поиск':'В архиве';$('caseStatus').className='case-status'+(item.status==='archive'?' archive':'');$('savedPoster').src=item.poster;$('caseActions').hidden=!currentIsAdmin();$('deleteCaseBtn').hidden=item.status!=='active';$('archiveCaseBtn').textContent=item.status==='active'?'Убрать в архив':'Сохранить архив на Google Drive';$('trackUploader').hidden=item.status!=='active';$('caseMessage').textContent='';$('pageSubtitle').textContent=item.title;if(updateHistory)history.pushState(null,'',`#case=${encodeURIComponent(id)}`);renderMenu();subscribeNotes(id);subscribeTracks(id);$('archiveCaseBtn').disabled=!(notesReady&&tracksReady);closeMenu();window.scrollTo({top:0,behavior:'smooth'})}
function route(){const params=new URLSearchParams(location.hash.slice(1)),id=params.get('case');if(id&&savedCases.some(item=>item.id===id))openCase(id);else if(params.get('view')==='create')showCreation();else showHome()}
function validateSavedCase(){const fields=[['lastName','фамилию'],['firstMiddleName','имя и отчество'],['age','возраст']];for(const [id,label] of fields){if(!val(id)){$('message').textContent=`Чтобы создать запись, укажите ${label}.`;$(id).focus();return false}}if(!bg.complete||!bg.naturalWidth){$('message').textContent='Шаблон ориентировки ещё загружается. Повторите через несколько секунд.';return false}return true}
function openSearchTypeDialog(){if(!currentIsAdmin()){$('message').textContent='Сохранять ориентировки в общую базу могут только администраторы.';return}if(!validateSavedCase())return;$('message').textContent='';$('searchTypeDialog').showModal()}
function withTimeout(promise,ms,code){let timer;return Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error(code)),ms)})]).finally(()=>clearTimeout(timer))}
function canvasBlob(quality){return new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',quality))}
async function posterBytes(){for(const quality of [.82,.72,.62,.52,.44]){const blob=await withTimeout(canvasBlob(quality),10000,'poster-timeout');if(blob&&blob.size<=768000)return new Uint8Array(await blob.arrayBuffer())}throw new Error('poster-too-large')}
function saveErrorText(error){if(error.message==='offline')return'Нет подключения к интернету. Черновик сохранён на этом устройстве.';if(error.message==='network-timeout')return'Firebase не отвечает. Проверьте подключение и повторите сохранение.';if(error.message==='save-timeout')return'Сервер слишком долго отвечает. Повторите сохранение: дубликат ориентировки не создастся.';if(error.message==='poster-timeout')return'Не удалось подготовить изображение. Обновите страницу и повторите.';if(error.message==='poster-too-large'||error.code==='resource-exhausted')return'Ориентировка получилась слишком большой. Попробуйте загрузить фото меньшего размера.';if(error.code==='permission-denied')return'Firebase отклонил сохранение. Обновите страницу и войдите заново.';return'Не удалось сохранить ориентировку. Проверьте интернет и повторите.'}
async function createSavedCase(type){if(savingCase)return;savingCase=true;$('saveCaseBtn').disabled=true;try{if(!navigator.onLine)throw new Error('offline');$('message').textContent='Проверяю подключение…';await withTimeout(getDocFromServer(doc(db,'users',currentUser.uid)),10000,'network-timeout');$('message').textContent='Подготавливаю ориентировку…';render();const data=formData(),title=makeCaseTitle(data),writeKey=type+'\n'+JSON.stringify(data),bytes=await posterBytes();if(!pendingCaseWrite||pendingCaseWrite.key!==writeKey)pendingCaseWrite={key:writeKey,ref:doc(collection(db,'cases'))};const ref=pendingCaseWrite.ref;$('message').textContent='Сохраняю ориентировку…';await withTimeout(setDoc(ref,{type,status:'active',title,data,poster:Bytes.fromUint8Array(bytes),createdAt:serverTimestamp(),createdBy:currentUser.uid,createdByEmail:currentUser.email||''}),20000,'save-timeout');pendingCaseWrite=null;resetForm();const poster=URL.createObjectURL(new Blob([bytes],{type:'image/jpeg'}));posterUrls.push(poster);savedCases=[{id:ref.id,type,status:'active',title,data,poster,posterBytes:bytes,createdAt:Date.now()},...savedCases.filter(item=>item.id!==ref.id)];openCase(ref.id,true)}catch(error){console.error(error);if(error.message!=='save-timeout')pendingCaseWrite=null;$('message').textContent=saveErrorText(error)}finally{savingCase=false;$('saveCaseBtn').disabled=false}}

function applyTheme(theme){const dark=theme==='dark';document.documentElement.dataset.theme=dark?'dark':'light';$('themeToggle').checked=dark;$('themeToggle').setAttribute('aria-label',dark?'Включена ночная тема. Переключить на дневную':'Включена дневная тема. Переключить на ночную');document.querySelector('meta[name="theme-color"]').content=dark?'#202326':'#b90000';try{localStorage.setItem(THEME_KEY,dark?'dark':'light')}catch{}}
function initialTheme(){try{return localStorage.getItem(THEME_KEY)==='dark'?'dark':'light'}catch{return'light'}}
function trackExtension(fileName){const normalized=String(fileName||'').toLowerCase();if(normalized.endsWith('.gpx.bin'))return'gpx.bin';const extension=normalized.split('.').pop();return TRACK_EXTENSIONS.has(extension)?extension:'file'}
function trackFileSize(bytes){if(!Number.isFinite(bytes))return'';if(bytes<1024)return`${bytes} Б`;if(bytes<1024*1024)return`${(bytes/1024).toFixed(bytes<10240?1:0)} КБ`;return`${(bytes/1024/1024).toFixed(1)} МБ`}
function trackDate(timestamp){if(!timestamp)return'Загружается…';return new Intl.DateTimeFormat('ru-RU',{dateStyle:'medium',timeStyle:'short'}).format(timestamp)}
function canManageTrack(track){return track.authorId===currentUser?.uid||currentIsAdmin()}
function trackSvg(kind){const namespace='http://www.w3.org/2000/svg',icon=document.createElementNS(namespace,'svg');icon.setAttribute('viewBox','0 0 24 24');icon.setAttribute('aria-hidden','true');const paths=kind==='open'?['M14 3h7v7','m10 4 7-7','M21 14v5a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5']:['M3 6h18','M8 6V4h8v2m3 0-1 15H6L5 6','M10 11v6m4-6v6'];paths.forEach(value=>{const path=document.createElementNS(namespace,'path');path.setAttribute('d',value);icon.append(path)});return icon}
function renderTracks(){const list=$('tracksList');list.replaceChildren();$('tracksCount').textContent=String(savedTracks.length);if(!savedTracks.length){const empty=document.createElement('div');empty.className='tracks-empty';empty.textContent=tracksReady?'Треков пока нет':'Загружаю треки…';list.append(empty);return}savedTracks.forEach(track=>{const item=document.createElement('article');item.className='track-item';const icon=document.createElement('span');icon.className='track-file-icon';icon.textContent=trackExtension(track.fileName);const info=document.createElement('div');info.className='track-info';const name=document.createElement('strong');name.textContent=track.fileName;const profile=userProfiles.get(track.authorId),author=profile?.displayName||track.authorName||track.authorEmail||'Пользователь',meta=document.createElement('span');meta.textContent=`${trackFileSize(track.fileSize)} · ${author} · ${trackDate(track.createdAtMs)}`;info.append(name,meta);const actions=document.createElement('div');actions.className='track-actions';const open=document.createElement('a');open.className='track-open';open.href=track.url;open.target='_blank';open.rel='noopener';open.title='Открыть или скачать трек';open.setAttribute('aria-label',`Открыть трек ${track.fileName}`);open.append(trackSvg('open'));const openText=document.createElement('span');openText.textContent='Открыть';open.append(openText);actions.append(open);if(canManageTrack(track)){const remove=document.createElement('button');remove.type='button';remove.className='track-delete';remove.title='Удалить трек';remove.setAttribute('aria-label',`Удалить трек ${track.fileName}`);remove.append(trackSvg('delete'));remove.onclick=()=>deleteTrack(track.id);actions.append(remove)}item.append(icon,info,actions);list.append(item)})}
function stopTracksSubscription(){if(unsubscribeTracks){unsubscribeTracks();unsubscribeTracks=null}tracksCaseId=null;tracksReady=false;savedTracks=[];$('tracksMessage').textContent='';$('trackFilesInput').value='';renderTracks()}
function subscribeTracks(caseId){if(unsubscribeTracks&&tracksCaseId===caseId)return;stopTracksSubscription();tracksCaseId=caseId;unsubscribeTracks=onSnapshot(query(collection(db,'tracks'),where('caseId','==',caseId)),snapshot=>{savedTracks=snapshot.docs.map(entry=>{const data=entry.data();return{id:entry.id,...data,createdAtMs:data.createdAt?.toMillis?.()||0}}).sort((a,b)=>b.createdAtMs-a.createdAtMs);tracksReady=true;if(currentCaseId===caseId&&!archivingCase)$('archiveCaseBtn').disabled=!notesReady;renderTracks()},error=>{console.error(error);tracksReady=false;$('tracksMessage').textContent='Не удалось загрузить треки.';renderTracks()})}
function trackErrorText(error){if(error.message==='offline')return'Нет подключения к интернету.';if(error.message==='track-count')return`За один раз можно загрузить не более ${MAX_TRACK_FILES} файлов.`;if(error.message==='track-type')return'Допустимы только файлы GPX, GPX.BIN, KML, KMZ, TCX и FIT.';if(error.message==='track-empty')return'Выбран пустой файл.';if(error.message==='track-large')return'Размер каждого трека должен быть не больше 15 МБ.';if(error.message==='track-upload-timeout')return'Google Drive слишком долго отвечает. Повторите загрузку.';if(error.message==='track-upload')return error.trackMessage||'Google Drive не принял файл.';return'Не удалось загрузить трек. Проверьте интернет и повторите.'}
async function postTrackAction(action,payload,responseType,timeout=120000){const idToken=await currentUser.getIdToken(),nonce=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`,frameName=`${responseType}-${nonce}`,iframe=document.createElement('iframe'),form=document.createElement('form');iframe.name=frameName;iframe.title=action==='uploadTrack'?'Загрузка трека':'Удаление трека';iframe.hidden=true;form.method='post';form.action=ARCHIVE_UPLOAD_URL;form.target=frameName;form.hidden=true;for(const [name,value] of Object.entries({action,nonce,idToken,...payload})){const input=document.createElement('input');input.type='hidden';input.name=name;input.value=String(value);form.append(input)}document.body.append(iframe,form);return new Promise((resolve,reject)=>{let timer;const cleanup=()=>{clearTimeout(timer);window.removeEventListener('message',receive);form.remove();iframe.remove()};const receive=event=>{if(!archiveFrameOriginAllowed(event.origin)||event.data?.type!==responseType||event.data.nonce!==nonce)return;cleanup();if(event.data.ok)resolve(event.data);else{const error=new Error(action==='uploadTrack'?'track-upload':'track-delete');error.trackMessage=event.data.error||'';reject(error)}};window.addEventListener('message',receive);timer=setTimeout(()=>{cleanup();reject(new Error(action==='uploadTrack'?'track-upload-timeout':'track-delete-timeout'))},timeout);form.submit()})}
async function uploadTrackFile(file){const extension=trackExtension(file.name);if(extension==='file')throw new Error('track-type');if(!file.size)throw new Error('track-empty');if(file.size>MAX_TRACK_FILE_BYTES)throw new Error('track-large');const fileBase64=await blobBase64(file),trackId=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;return postTrackAction('uploadTrack',{trackId,caseId:currentCaseId,fileName:file.name,fileType:file.type||'application/octet-stream',fileSize:file.size,fileBase64},'kpc-track-upload')}
async function uploadTracks(files){if(uploadingTracks||!currentCaseId)return 0;const selected=[...files];if(!selected.length)return 0;if(selected.length>MAX_TRACK_FILES){$('tracksMessage').textContent=trackErrorText(new Error('track-count'));return 0}for(const file of selected){if(trackExtension(file.name)==='file'){$('tracksMessage').textContent=`${file.name}: ${trackErrorText(new Error('track-type'))}`;return 0}if(!file.size||file.size>MAX_TRACK_FILE_BYTES){$('tracksMessage').textContent=`${file.name}: ${trackErrorText(new Error(file.size?'track-large':'track-empty'))}`;return 0}}if(!navigator.onLine){$('tracksMessage').textContent=trackErrorText(new Error('offline'));return 0}uploadingTracks=true;$('trackFilesInput').disabled=true;let completed=0;try{for(const file of selected){$('tracksMessage').textContent=`Загружаю ${completed+1} из ${selected.length}: ${file.name}`;await uploadTrackFile(file);completed+=1}$('tracksMessage').textContent=completed===1?'Трек загружен.':`Загружено файлов: ${completed}.`}catch(error){console.error(error);$('tracksMessage').textContent=`Загружено ${completed} из ${selected.length}. ${trackErrorText(error)}`}finally{uploadingTracks=false;$('trackFilesInput').disabled=false;$('trackFilesInput').value=''}return completed}
function deleteTrack(id){const track=savedTracks.find(entry=>entry.id===id);if(!track||!canManageTrack(track))return;askConfirmation({title:'Удалить трек?',text:`Файл «${track.fileName}» будет удалён из поиска и с Google Drive без возможности восстановления.`,label:'Удалить',action:async()=>{try{$('tracksMessage').textContent='Удаляю трек…';await postTrackAction('deleteTrack',{trackId:id},'kpc-track-delete',60000);$('tracksMessage').textContent='Трек удалён.'}catch(error){console.error(error);$('tracksMessage').textContent=error.trackMessage||'Не удалось удалить трек. Повторите попытку.'}}})}

function removeSharedTracksQuery(){const url=new URL(location.href);url.searchParams.delete('sharedTracks');history.replaceState(null,'',url.pathname+(url.search||'')+(url.hash||''));sharedTracksBatch=''}
async function cleanupSharedTracks(){if(!sharedTracksBatch)return;try{const cache=await caches.open(SHARED_TRACKS_CACHE);await Promise.all([...sharedTracksMetadata.map(file=>cache.delete(file.url)),cache.delete(new URL(`shared-tracks/${sharedTracksBatch}/meta`,location.href).href)])}catch(error){console.error(error)}sharedTracksMetadata=[];sharedTracksFiles=[];removeSharedTracksQuery()}
async function readSharedTracks(){if(!/^[A-Za-z0-9-]{6,100}$/.test(sharedTracksBatch))throw new Error('share-id');const metaUrl=new URL(`shared-tracks/${sharedTracksBatch}/meta`,location.href).href,response=await fetch(metaUrl,{cache:'no-store'});if(!response.ok)throw new Error('share-missing');const payload=await response.json();sharedTracksMetadata=Array.isArray(payload.files)?payload.files.slice(0,MAX_TRACK_FILES+1):[];sharedTracksFiles=[];for(const metadata of sharedTracksMetadata){const fileResponse=await fetch(metadata.url,{cache:'no-store'});if(!fileResponse.ok)throw new Error('share-missing');const blob=await fileResponse.blob();sharedTracksFiles.push(new File([blob],metadata.name,{type:metadata.type||blob.type||'application/octet-stream'}))}}
function renderSharedTracksDialog(){const container=$('sharedTracksFiles'),select=$('sharedTracksCaseSelect'),activeCases=savedCases.filter(item=>item.status==='active').sort((a,b)=>b.createdAt-a.createdAt);container.replaceChildren();sharedTracksFiles.forEach(file=>{const row=document.createElement('div');row.className='shared-track-file';const name=document.createElement('strong');name.textContent=file.name;const size=document.createElement('span');size.textContent=trackFileSize(file.size);row.append(name,size);container.append(row)});select.replaceChildren();activeCases.forEach(item=>{const option=document.createElement('option');option.value=item.id;option.textContent=`${item.type} · ${item.title}`;select.append(option)});const invalid=sharedTracksFiles.length>MAX_TRACK_FILES||sharedTracksFiles.some(file=>trackExtension(file.name)==='file'||!file.size||file.size>MAX_TRACK_FILE_BYTES);$('sharedTracksUploadBtn').disabled=!activeCases.length||invalid;$('sharedTracksMessage').textContent=!activeCases.length?'Нет активных поисков для загрузки.':sharedTracksFiles.length>MAX_TRACK_FILES?`Получено больше ${MAX_TRACK_FILES} файлов. Отправьте меньшее количество.`:invalid?'Среди полученных файлов есть неподдерживаемый формат или слишком большой файл.':''}
async function maybeOpenSharedTracks(){if(sharedTracksOpened||!sharedTracksBatch||!currentProfile?.approved)return;sharedTracksOpened=true;try{await readSharedTracks();if(!sharedTracksFiles.length)throw new Error('share-empty');renderSharedTracksDialog();$('sharedTracksDialog').showModal()}catch(error){console.error(error);await cleanupSharedTracks();alert('Не удалось получить переданные треки. Откройте файловый менеджер и отправьте их повторно.')}}
async function closeSharedTracks(){if($('sharedTracksDialog').open)$('sharedTracksDialog').close();await cleanupSharedTracks()}

const NOTE_ALLOWED_TAGS=new Set(['B','STRONG','I','EM','U','UL','OL','LI','P','DIV','BR']);
const NOTE_REMOVED_TAGS=new Set(['SCRIPT','STYLE','IFRAME','OBJECT','EMBED','LINK','META','IMG','VIDEO']);
function sanitizeNoteHtml(html){const template=document.createElement('template');template.innerHTML=html||'';const clean=node=>{[...node.childNodes].forEach(child=>{if(child.nodeType===Node.COMMENT_NODE){child.remove();return}if(child.nodeType!==Node.ELEMENT_NODE)return;if(NOTE_REMOVED_TAGS.has(child.tagName)){child.remove();return}clean(child);if(!NOTE_ALLOWED_TAGS.has(child.tagName))child.replaceWith(...child.childNodes);else[...child.attributes].forEach(attribute=>child.removeAttribute(attribute.name))})};clean(template.content);return template.innerHTML}
function notePlainText(html){const box=document.createElement('div');box.innerHTML=html;return(box.textContent||'').replace(/\u00a0/g,' ').trim()}
function revokeNoteUrls(){noteUrls.forEach(URL.revokeObjectURL);noteUrls=[]}
function releaseEditorImage(){if(noteImageAttachment?.url)URL.revokeObjectURL(noteImageAttachment.url);noteImageAttachment=null}
function setEditorImage(bytes,type='image/jpeg'){releaseEditorImage();if(bytes?.length){const url=URL.createObjectURL(new Blob([bytes],{type}));noteImageAttachment={bytes,type,url}}renderNoteAttachment()}
function renderNoteAttachment(){const hasImage=!!noteImageAttachment;$('noteAttachments').hidden=!hasImage;$('noteImagePreviewWrap').hidden=!hasImage;if(hasImage)$('noteImagePreview').src=noteImageAttachment.url;else $('noteImagePreview').removeAttribute('src')}
function resetNoteComposer(clearMessage=true){editingNoteId=null;$('noteEditor').innerHTML='';$('notePhotoInput').value='';releaseEditorImage();renderNoteAttachment();$('saveNoteBtn').textContent='Добавить заметку';$('cancelNoteEditBtn').hidden=true;if(clearMessage)$('noteMessage').textContent=''}
function noteDate(timestamp){if(!timestamp)return'Сохраняется…';return new Intl.DateTimeFormat('ru-RU',{dateStyle:'medium',timeStyle:'short'}).format(timestamp)}
function canManageNote(note){return note.authorId===currentUser?.uid||currentIsAdmin()}
function avatarElement(profile,name,className){const avatar=document.createElement('span');avatar.className=className;if(profile?.photoUrl){const image=document.createElement('img');image.src=profile.photoUrl;image.alt='';avatar.append(image)}else{const fallback=document.createElement('span');fallback.textContent=(name||'П').trim().slice(0,1).toUpperCase();fallback.setAttribute('aria-hidden','true');avatar.append(fallback)}return avatar}
function noteAuthor(note){const profile=userProfiles.get(note.authorId);return profile?.displayName||note.authorName||note.authorEmail||'Пользователь'}
function renderNotes(){const list=$('notesList');list.replaceChildren();$('notesCount').textContent=String(savedNotes.length);if(!savedNotes.length){const empty=document.createElement('div');empty.className='notes-empty';empty.textContent='Заметок пока нет';list.append(empty);return}savedNotes.forEach(note=>{const profile=userProfiles.get(note.authorId),displayName=noteAuthor(note),article=document.createElement('article');article.className='note-item';const head=document.createElement('div');head.className='note-item-head';const avatar=avatarElement(profile,displayName,'note-avatar');const author=document.createElement('div');author.className='note-author';const authorName=document.createElement('strong');authorName.textContent=displayName;const authorEmail=document.createElement('span');authorEmail.textContent=note.authorEmail||profile?.email||'';author.append(authorName,authorEmail);const date=document.createElement('div');date.className='note-date';date.textContent=noteDate(note.createdAtMs);if(note.updatedAtMs&&note.createdAtMs&&note.updatedAtMs-note.createdAtMs>1000)date.textContent+=' · изменено';head.append(avatar,author,date);const content=document.createElement('div');content.className='note-content';content.innerHTML=sanitizeNoteHtml(note.contentHtml);article.append(head,content);if(note.imageUrl){const media=document.createElement('div');media.className='note-item-media';const link=document.createElement('a');link.href=note.imageUrl;link.target='_blank';link.rel='noopener';const image=document.createElement('img');image.src=note.imageUrl;image.alt='Фото к заметке';link.append(image);media.append(link);article.append(media)}if(canManageNote(note)){const actions=document.createElement('div');actions.className='note-item-actions';const edit=document.createElement('button');edit.type='button';edit.textContent='Редактировать';edit.onclick=()=>editNote(note.id);const remove=document.createElement('button');remove.type='button';remove.className='delete-note';remove.textContent='Удалить';remove.onclick=()=>deleteNote(note.id);actions.append(edit,remove);article.append(actions)}list.append(article)})}
function stopNotesSubscription(){if(unsubscribeNotes){unsubscribeNotes();unsubscribeNotes=null}notesCaseId=null;notesReady=false;revokeNoteUrls();savedNotes=[];resetNoteComposer();renderNotes()}
function subscribeNotes(caseId){if(unsubscribeNotes&&notesCaseId===caseId)return;stopNotesSubscription();notesCaseId=caseId;unsubscribeNotes=onSnapshot(query(collection(db,'notes'),where('caseId','==',caseId)),snapshot=>{revokeNoteUrls();savedNotes=snapshot.docs.map(entry=>{const data=entry.data(),imageBytes=data.image?.toUint8Array?.()||new Uint8Array();let imageUrl='';if(imageBytes.length){imageUrl=URL.createObjectURL(new Blob([imageBytes],{type:data.imageType||'image/jpeg'}));noteUrls.push(imageUrl)}return{id:entry.id,...data,imageBytes,imageUrl,createdAtMs:data.createdAt?.toMillis?.()||0,updatedAtMs:data.updatedAt?.toMillis?.()||0}}).sort((a,b)=>b.createdAtMs-a.createdAtMs);notesReady=true;if(currentCaseId===caseId&&!archivingCase)$('archiveCaseBtn').disabled=!tracksReady;renderNotes()},error=>{console.error(error);notesReady=false;$('noteMessage').textContent='Не удалось загрузить заметки.'})}
function loadImageFile(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),image=new Image();image.onload=()=>{URL.revokeObjectURL(url);resolve(image)};image.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('image-load'))};image.src=url})}
function noteCanvasBlob(canvas,quality){return new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',quality))}
async function compressNotePhoto(file){if(file.size>15*1024*1024)throw new Error('image-source-large');const image=await loadImageFile(file),maxSide=1600,scale=Math.min(1,maxSide/Math.max(image.naturalWidth,image.naturalHeight)),photoCanvas=document.createElement('canvas');photoCanvas.width=Math.max(1,Math.round(image.naturalWidth*scale));photoCanvas.height=Math.max(1,Math.round(image.naturalHeight*scale));photoCanvas.getContext('2d').drawImage(image,0,0,photoCanvas.width,photoCanvas.height);for(const quality of [.84,.72,.6,.48]){const blob=await withTimeout(noteCanvasBlob(photoCanvas,quality),10000,'image-timeout');if(blob&&blob.size<=600000)return new Uint8Array(await blob.arrayBuffer())}throw new Error('image-large')}
function noteErrorText(error){if(error.message==='offline')return'Нет подключения к интернету.';if(error.message==='note-empty')return'Добавьте текст или фотографию.';if(error.message==='note-long')return'Текст заметки слишком большой.';if(error.message==='image-source-large')return'Исходный файл больше 15 МБ. Выберите другое фото.';if(error.message==='image-large'||error.code==='resource-exhausted')return'Не удалось уменьшить фотографию до допустимого размера.';if(error.message==='image-timeout')return'Фотография обрабатывается слишком долго. Выберите другое фото.';if(error.message==='save-timeout')return'Firebase слишком долго отвечает. Повторите сохранение.';if(error.code==='permission-denied')return'Недостаточно прав для изменения этой заметки.';return'Не удалось сохранить заметку. Проверьте интернет и повторите.'}
async function saveNote(){if(savingNote||!currentCaseId)return;const contentHtml=sanitizeNoteHtml($('noteEditor').innerHTML),hasText=!!notePlainText(contentHtml),imageBytes=noteImageAttachment?.bytes||new Uint8Array();if(!hasText&&!imageBytes.length){$('noteMessage').textContent=noteErrorText(new Error('note-empty'));return}if(contentHtml.length>20000){$('noteMessage').textContent=noteErrorText(new Error('note-long'));return}if(!navigator.onLine){$('noteMessage').textContent=noteErrorText(new Error('offline'));return}savingNote=true;$('saveNoteBtn').disabled=true;$('noteMessage').textContent=editingNoteId?'Сохраняю изменения…':'Добавляю заметку…';try{const editable={contentHtml,image:Bytes.fromUint8Array(imageBytes),imageType:imageBytes.length?'image/jpeg':'',updatedAt:serverTimestamp()};if(editingNoteId)await withTimeout(updateDoc(doc(db,'notes',editingNoteId),editable),20000,'save-timeout');else{const ref=doc(collection(db,'notes'));await withTimeout(setDoc(ref,{caseId:currentCaseId,...editable,authorId:currentUser.uid,authorName:currentProfile?.displayName||currentUser.displayName||(currentUser.email||'').split('@')[0]||'Пользователь',authorEmail:currentUser.email||'',createdAt:serverTimestamp()}),20000,'save-timeout')}resetNoteComposer(false);$('noteMessage').textContent='Заметка сохранена.'}catch(error){console.error(error);$('noteMessage').textContent=noteErrorText(error)}finally{savingNote=false;$('saveNoteBtn').disabled=false}}
function editNote(id){const note=savedNotes.find(entry=>entry.id===id);if(!note||!canManageNote(note))return;editingNoteId=id;$('noteEditor').innerHTML=sanitizeNoteHtml(note.contentHtml);setEditorImage(note.imageBytes,note.imageType||'image/jpeg');$('saveNoteBtn').textContent='Сохранить изменения';$('cancelNoteEditBtn').hidden=false;$('noteMessage').textContent='Редактирование заметки';$('noteComposer').scrollIntoView({behavior:'smooth',block:'start'});$('noteEditor').focus({preventScroll:true})}
function deleteNote(id){const note=savedNotes.find(entry=>entry.id===id);if(!note||!canManageNote(note))return;askConfirmation({title:'Удалить заметку?',text:'Заметка и прикреплённая фотография будут удалены без возможности восстановления.',label:'Удалить',action:async()=>{try{await deleteDoc(doc(db,'notes',id));if(editingNoteId===id)resetNoteComposer()}catch(error){console.error(error);$('noteMessage').textContent='Не удалось удалить заметку.'}}})}

const ARCHIVE_PAGE_WIDTH=1240,ARCHIVE_PAGE_HEIGHT=1754,ARCHIVE_MARGIN=76;
function archiveCanvas(title,subtitle){const page=document.createElement('canvas');page.width=ARCHIVE_PAGE_WIDTH;page.height=ARCHIVE_PAGE_HEIGHT;const pageCtx=page.getContext('2d');pageCtx.fillStyle='#fff';pageCtx.fillRect(0,0,page.width,page.height);pageCtx.fillStyle='#bd0000';pageCtx.fillRect(ARCHIVE_MARGIN,58,page.width-ARCHIVE_MARGIN*2,8);pageCtx.fillStyle='#202124';pageCtx.font='700 38px Arial, sans-serif';archiveFitText(pageCtx,title,ARCHIVE_MARGIN,125,page.width-ARCHIVE_MARGIN*2,38,27);pageCtx.fillStyle='#707078';pageCtx.font='24px Arial, sans-serif';pageCtx.fillText(subtitle,ARCHIVE_MARGIN,168);pageCtx.strokeStyle='#e1e3e5';pageCtx.beginPath();pageCtx.moveTo(ARCHIVE_MARGIN,194);pageCtx.lineTo(page.width-ARCHIVE_MARGIN,194);pageCtx.stroke();return{page,pageCtx}}
function archiveFitText(pageCtx,text,x,y,maxWidth,start,min){let size=start;pageCtx.font=`700 ${size}px Arial, sans-serif`;while(pageCtx.measureText(text).width>maxWidth&&size>min){size-=1;pageCtx.font=`700 ${size}px Arial, sans-serif`}pageCtx.fillText(text,x,y)}
function archiveWrappedLines(pageCtx,text,maxWidth){const lines=[];for(const paragraph of String(text||'').replace(/\r/g,'').split('\n')){const words=paragraph.trim().split(/\s+/).filter(Boolean);if(!words.length){lines.push('');continue}let line='';for(let word of words){while(pageCtx.measureText(word).width>maxWidth){let part='';for(const char of word){if(part&&pageCtx.measureText(part+char).width>maxWidth)break;part+=char}if(line){lines.push(line);line=''}lines.push(part);word=word.slice(part.length)}const candidate=line?`${line} ${word}`:word;if(line&&pageCtx.measureText(candidate).width>maxWidth){lines.push(line);line=word}else line=candidate}if(line)lines.push(line)}return lines}
function archiveNoteText(html){const box=document.createElement('div');box.innerHTML=sanitizeNoteHtml(html);box.style.cssText='position:fixed;left:-10000px;top:0;width:700px;white-space:normal';document.body.append(box);const text=(box.innerText||box.textContent||'').replace(/\u00a0/g,' ').trim();box.remove();return text}
function archiveTextPages(item,note){const author=note.authorName||note.authorEmail||'Пользователь',date=noteDate(note.createdAtMs),text=archiveNoteText(note.contentHtml);if(!text)return[];const probe=document.createElement('canvas').getContext('2d');probe.font='30px Arial, sans-serif';const lines=archiveWrappedLines(probe,text,ARCHIVE_PAGE_WIDTH-ARCHIVE_MARGIN*2),pages=[],maxLines=29;for(let offset=0;offset<lines.length;offset+=maxLines){const {page,pageCtx}=archiveCanvas(item.title,`${item.type} · Архивная заметка`);pageCtx.fillStyle='#202124';pageCtx.font='700 28px Arial, sans-serif';pageCtx.fillText(author,ARCHIVE_MARGIN,250);pageCtx.fillStyle='#73777b';pageCtx.font='21px Arial, sans-serif';pageCtx.fillText(date,ARCHIVE_MARGIN,286);pageCtx.fillStyle='#202124';pageCtx.font='30px Arial, sans-serif';lines.slice(offset,offset+maxLines).forEach((line,index)=>{if(line)pageCtx.fillText(line,ARCHIVE_MARGIN,354+index*44)});pages.push(page.toDataURL('image/jpeg',.82))}return pages}
async function archivePhotoPage(item,note){if(!note.imageBytes?.length)return null;const {page,pageCtx}=archiveCanvas(item.title,`${item.type} · Фотография к заметке`),image=await loadImageFile(new Blob([note.imageBytes],{type:note.imageType||'image/jpeg'})),author=note.authorName||note.authorEmail||'Пользователь';pageCtx.fillStyle='#202124';pageCtx.font='700 28px Arial, sans-serif';pageCtx.fillText(author,ARCHIVE_MARGIN,250);pageCtx.fillStyle='#73777b';pageCtx.font='21px Arial, sans-serif';pageCtx.fillText(noteDate(note.createdAtMs),ARCHIVE_MARGIN,286);const area={x:ARCHIVE_MARGIN,y:330,w:page.width-ARCHIVE_MARGIN*2,h:page.height-410},scale=Math.min(area.w/image.naturalWidth,area.h/image.naturalHeight),width=image.naturalWidth*scale,height=image.naturalHeight*scale;pageCtx.drawImage(image,area.x+(area.w-width)/2,area.y+(area.h-height)/2,width,height);return page.toDataURL('image/jpeg',.82)}
function archiveTrackPage(item,tracks,startIndex){const {page,pageCtx}=archiveCanvas(item.title,`${item.type} · Треки поиска`),links=[];let y=260;tracks.forEach((track,index)=>{pageCtx.fillStyle='#202124';pageCtx.font='700 27px Arial, sans-serif';const lines=archiveWrappedLines(pageCtx,`${startIndex+index+1}. ${track.fileName}`,page.width-ARCHIVE_MARGIN*2).slice(0,2);lines.forEach((line,lineIndex)=>pageCtx.fillText(line,ARCHIVE_MARGIN,y+lineIndex*34));y+=lines.length*34+6;pageCtx.fillStyle='#707078';pageCtx.font='20px Arial, sans-serif';pageCtx.fillText(`${track.authorName||track.authorEmail||'Пользователь'} · ${trackFileSize(track.fileSize)}`,ARCHIVE_MARGIN,y);y+=34;pageCtx.fillStyle='#2d667e';pageCtx.font='700 21px Arial, sans-serif';pageCtx.fillText('Открыть или скачать трек',ARCHIVE_MARGIN,y);pageCtx.strokeStyle='#2d667e';pageCtx.lineWidth=1;pageCtx.beginPath();pageCtx.moveTo(ARCHIVE_MARGIN,y+4);pageCtx.lineTo(ARCHIVE_MARGIN+250,y+4);pageCtx.stroke();links.push({x:ARCHIVE_MARGIN,y:y-24,w:260,h:32,url:track.url});y+=70});return{image:page.toDataURL('image/jpeg',.86),links}}
function addArchiveTrackPages(pdf,item){const tracks=savedTracks.slice().sort((a,b)=>a.createdAtMs-b.createdAtMs),perPage=8;for(let offset=0;offset<tracks.length;offset+=perPage){const page=archiveTrackPage(item,tracks.slice(offset,offset+perPage),offset);pdf.addPage([ARCHIVE_PAGE_WIDTH,ARCHIVE_PAGE_HEIGHT],'portrait');pdf.addImage(page.image,'JPEG',0,0,ARCHIVE_PAGE_WIDTH,ARCHIVE_PAGE_HEIGHT,undefined,'FAST');page.links.forEach(link=>pdf.link(link.x,link.y,link.w,link.h,{url:link.url}))}}
async function buildArchivePdf(item){if(!window.jspdf?.jsPDF)throw new Error('pdf-library');if(!item.posterBytes?.length)throw new Error('poster-missing');const {jsPDF}=window.jspdf,pdf=new jsPDF({orientation:'portrait',unit:'px',format:[ARCHIVE_PAGE_WIDTH,ARCHIVE_PAGE_HEIGHT],compress:true,hotfixes:['px_scaling']}),posterWidth=ARCHIVE_PAGE_HEIGHT*(1024/1536),posterX=(ARCHIVE_PAGE_WIDTH-posterWidth)/2;pdf.setProperties({title:item.title,subject:`Архивная ориентировка ${item.type}`,creator:'КПЦ Симбирск'});pdf.addImage(item.posterBytes,'JPEG',posterX,0,posterWidth,ARCHIVE_PAGE_HEIGHT,undefined,'FAST');const notes=[...savedNotes].sort((a,b)=>a.createdAtMs-b.createdAtMs);for(let index=0;index<notes.length;index+=1){$('caseMessage').textContent=`Формирую PDF: заметка ${index+1} из ${notes.length}…`;for(const page of archiveTextPages(item,notes[index])){pdf.addPage([ARCHIVE_PAGE_WIDTH,ARCHIVE_PAGE_HEIGHT],'portrait');pdf.addImage(page,'JPEG',0,0,ARCHIVE_PAGE_WIDTH,ARCHIVE_PAGE_HEIGHT,undefined,'FAST')}const photoPage=await archivePhotoPage(item,notes[index]);if(photoPage){pdf.addPage([ARCHIVE_PAGE_WIDTH,ARCHIVE_PAGE_HEIGHT],'portrait');pdf.addImage(photoPage,'JPEG',0,0,ARCHIVE_PAGE_WIDTH,ARCHIVE_PAGE_HEIGHT,undefined,'FAST')}}addArchiveTrackPages(pdf,item);return pdf.output('blob')}
function archiveFileName(item){const safe=String(item.title).replace(/[\\/:*?"<>|]/g,' ').replace(/\s+/g,' ').trim();return `${item.type} — ${safe}.pdf`}
function blobBase64(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.onerror=()=>reject(new Error('archive-encode'));reader.readAsDataURL(blob)})}
function archiveFrameOriginAllowed(origin){try{const url=new URL(origin),host=url.hostname;return url.protocol==='https:'&&(host==='script.google.com'||host==='script.googleusercontent.com'||host.endsWith('-script.googleusercontent.com'))}catch{return false}}
async function deleteAuthenticationUser(userId){const idToken=await currentUser.getIdToken(),nonce=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`,frameName=`kpc-user-delete-${nonce}`,iframe=document.createElement('iframe'),form=document.createElement('form');iframe.name=frameName;iframe.title='Удаление учетной записи';iframe.hidden=true;form.method='post';form.action=ARCHIVE_UPLOAD_URL;form.target=frameName;form.hidden=true;for(const [name,value] of Object.entries({action:'deleteAuthUser',nonce,idToken,targetUserId:userId})){const input=document.createElement('input');input.type='hidden';input.name=name;input.value=value;form.append(input)}document.body.append(iframe,form);return new Promise((resolve,reject)=>{let timer;const cleanup=()=>{clearTimeout(timer);window.removeEventListener('message',receive);form.remove();iframe.remove()};const receive=event=>{if(!archiveFrameOriginAllowed(event.origin)||event.data?.type!=='kpc-user-delete'||event.data.nonce!==nonce)return;cleanup();if(event.data.ok)resolve();else{const error=new Error('auth-user-delete');error.userMessage=event.data.error||'';reject(error)}};window.addEventListener('message',receive);timer=setTimeout(()=>{cleanup();reject(new Error('auth-user-delete-timeout'))},45000);form.submit()})}
async function uploadArchivePdf(item,pdf,fileName){if(pdf.size>35*1024*1024)throw new Error('archive-upload-large');const idToken=await currentUser.getIdToken(),pdfBase64=await blobBase64(pdf),nonce=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`,frameName=`kpc-archive-${nonce}`,iframe=document.createElement('iframe'),form=document.createElement('form');iframe.name=frameName;iframe.title='Загрузка архива';iframe.hidden=true;form.method='post';form.action=ARCHIVE_UPLOAD_URL;form.target=frameName;form.hidden=true;for(const [name,value] of Object.entries({nonce,idToken,caseId:item.id,fileName,pdfBase64})){const input=document.createElement('input');input.type='hidden';input.name=name;input.value=value;form.append(input)}document.body.append(iframe,form);return new Promise((resolve,reject)=>{let timer;const cleanup=()=>{clearTimeout(timer);window.removeEventListener('message',receive);form.remove();iframe.remove()};const receive=event=>{if(!archiveFrameOriginAllowed(event.origin)||event.data?.type!=='kpc-drive-archive'||event.data.nonce!==nonce)return;cleanup();if(event.data.ok&&event.data.file?.id&&event.data.file?.webViewLink)resolve(event.data.file);else{const error=new Error('archive-upload');error.archiveMessage=event.data.error||'';reject(error)}};window.addEventListener('message',receive);timer=setTimeout(()=>{cleanup();reject(new Error('archive-upload-timeout'))},120000);form.submit()})}
function archiveErrorText(error){if(error.message==='archive-notes-loading')return'Заметки или треки ещё загружаются. Подождите несколько секунд и повторите.';if(error.message==='offline')return'Нет подключения к интернету.';if(error.message==='pdf-library'||error.message==='poster-missing'||error.message==='archive-encode')return'Не удалось подготовить PDF. Обновите страницу и повторите.';if(error.message==='archive-upload-large')return'Архив получился больше 35 МБ. Уменьшите количество или размер фотографий.';if(error.message==='archive-upload-timeout')return'Загрузчик Google Drive не ответил. Проверьте доступ веб-приложения «Все» и повторите.';if(error.message==='archive-upload')return error.archiveMessage||'Google Drive не принял PDF. Повторите архивирование.';if(error.code==='permission-denied')return'Firebase не разрешил завершить перенос. PDF уже может находиться на Диске, а исходная ориентировка сохранена.';return'Не удалось перенести ориентировку. Исходная запись сохранена в Firebase.'}
async function completeDriveArchive(item,file){const noteIds=savedNotes.map(note=>note.id),trackIds=savedTracks.map(track=>track.id);await updateDoc(doc(db,'cases',item.id),{status:'archive',archiveUrl:file.webViewLink,driveFileId:file.id,archiveFileName:file.name,archivedAt:serverTimestamp(),archivedBy:currentUser.uid,poster:deleteField(),data:deleteField(),createdByEmail:deleteField()});const cleanup=await Promise.allSettled([...noteIds.map(id=>deleteDoc(doc(db,'notes',id))),...trackIds.map(id=>deleteDoc(doc(db,'tracks',id)))]);cleanup.filter(result=>result.status==='rejected').forEach(result=>console.error('Archive cleanup failed',result.reason))}

function askConfirmation({title,text,label,kind='danger',action}){$('confirmTitle').textContent=title;$('confirmText').textContent=text;$('confirmAcceptBtn').textContent=label;$('confirmAcceptBtn').className=kind;pendingConfirm=action;$('confirmDialog').showModal()}
function deleteCurrentCase(){const item=savedCases.find(entry=>entry.id===currentCaseId);if(!item)return;askConfirmation({title:'Удалить ориентировку?',text:`Запись «${item.title}», её заметки, фотографии и треки будут удалены без возможности восстановления.`,label:'Удалить',action:async()=>{try{const noteIds=savedNotes.map(note=>note.id),trackIds=savedTracks.map(track=>track.id);$('caseMessage').textContent='Удаляю файлы поиска…';for(const trackId of trackIds)await postTrackAction('deleteTrack',{trackId},'kpc-track-delete',60000);await deleteDoc(doc(db,'cases',item.id));await Promise.allSettled(noteIds.map(id=>deleteDoc(doc(db,'notes',id))));showCreation(true)}catch(error){console.error(error);$('caseMessage').textContent=error.trackMessage||'Не удалось удалить ориентировку.'}}})}
function archiveCurrentCase(){const item=savedCases.find(entry=>entry.id===currentCaseId);if(!item||archivingCase)return;const migrating=item.status==='archive';askConfirmation({title:migrating?'Сохранить архив на Google Drive?':'Убрать ориентировку в архив?',text:'Будет создан PDF с ориентировкой, заметками, фотографиями и ссылками на треки. После загрузки тяжёлые данные удалятся из Firebase, а треки останутся на Google Drive.',label:migrating?'Сохранить на Диск':'Убрать в архив',kind:'primary',action:async()=>{archivingCase=true;$('archiveCaseBtn').disabled=true;$('deleteCaseBtn').disabled=true;$('caseMessage').textContent='Подготавливаю архив…';try{if(!navigator.onLine)throw new Error('offline');if(!notesReady||notesCaseId!==item.id||!tracksReady||tracksCaseId!==item.id)throw new Error('archive-notes-loading');const pdf=await buildArchivePdf(item),fileName=archiveFileName(item);$('caseMessage').textContent='Загружаю PDF на Google Drive…';const driveFile=await uploadArchivePdf(item,pdf,fileName);$('caseMessage').textContent='Освобождаю место в Firebase…';await completeDriveArchive(item,driveFile);const groups=document.querySelectorAll('.menu-group');if(groups.length>1)groups[1].open=true;showCreation(true)}catch(error){console.error(error);$('caseMessage').textContent=archiveErrorText(error)}finally{archivingCase=false;$('archiveCaseBtn').disabled=!(notesReady&&tracksReady);$('deleteCaseBtn').disabled=false}}})}

function profileBytes(profile){return profile?.photo?.toUint8Array?.()||new Uint8Array()}
function setAvatarImage(image,fallback,url){image.hidden=!url;fallback.hidden=!!url;if(url)image.src=url;else image.removeAttribute('src')}
function profileRoleLabel(){if(currentIsOwner())return'Владелец';return currentIsAdmin()?'Администратор':'Пользователь'}
function renderCurrentProfile(){if(!currentUser||!currentProfile)return;if(currentProfilePhotoUrl)URL.revokeObjectURL(currentProfilePhotoUrl);const bytes=profileBytes(currentProfile);currentProfilePhotoUrl=bytes.length?URL.createObjectURL(new Blob([bytes],{type:currentProfile.photoType||'image/jpeg'})):null;const name=currentProfile.displayName||currentUser.displayName||currentUser.email||'Пользователь';$('currentUserName').textContent=name;$('currentUserEmail').textContent=currentUser.email||'';$('profileDisplayName').textContent=name;$('profileEmail').textContent=currentUser.email||'';$('profileRole').textContent=profileRoleLabel();setAvatarImage($('menuAvatar'),$('menuAvatarFallback'),currentProfilePhotoUrl);setAvatarImage($('profileAvatar'),$('profileAvatarFallback'),currentProfilePhotoUrl);$('removeProfilePhotoBtn').hidden=!currentProfilePhotoUrl}
function renderProfileProviders(){if(!currentUser)return;const providers=new Set(currentUser.providerData.map(item=>item.providerId)),hasEmail=providers.has('password'),hasGoogle=providers.has('google.com');$('emailProviderState').textContent=hasEmail?'Почта подключена':'Почта не подключена';$('emailProviderState').className='provider-state'+(hasEmail?' connected':'');$('googleProviderState').textContent=hasGoogle?'Google подключен':'Google не подключен';$('googleProviderState').className='provider-state'+(hasGoogle?' connected':'');$('profilePasswordSection').hidden=!hasEmail;$('linkEmailForm').hidden=hasEmail;$('linkGoogleBtn').hidden=hasGoogle;$('linkEmailAddress').textContent=currentUser.email||''}
function setProfileMessage(text='',success=false){$('profileMessage').textContent=text;$('profileMessage').className='profile-message'+(success?' success':'')}
function openProfile(){if(!currentUser||!currentProfile)return;closeMenu();$('profileName').value=currentProfile.displayName||currentUser.displayName||'';$('profileNewPassword').value='';$('profileConfirmPassword').value='';$('linkEmailPassword').value='';$('linkEmailPasswordConfirm').value='';setProfileMessage();renderCurrentProfile();renderProfileProviders();$('profileDialog').showModal()}
function profileErrorText(error){const messages={'auth/requires-recent-login':'Для этого изменения нужно заново войти в аккаунт, затем повторить действие.','auth/credential-already-in-use':'Этот способ входа уже связан с другой учетной записью.','auth/provider-already-linked':'Этот способ входа уже подключен.','auth/email-already-in-use':'Этот email уже используется другой учетной записью.','auth/weak-password':'Пароль должен содержать не менее 6 символов.','auth/popup-closed-by-user':'Окно Google было закрыто.','auth/popup-blocked':'Браузер заблокировал окно Google. Разрешите всплывающие окна.','permission-denied':'Firebase не разрешил изменить профиль.'};return messages[error.code]||'Не удалось изменить профиль. Проверьте интернет и повторите.'}
async function compressProfilePhoto(file){if(file.size>10*1024*1024)throw new Error('profile-photo-source-large');const image=await loadImageFile(file),side=Math.min(image.naturalWidth,image.naturalHeight),sourceX=(image.naturalWidth-side)/2,sourceY=(image.naturalHeight-side)/2,photoCanvas=document.createElement('canvas');photoCanvas.width=320;photoCanvas.height=320;photoCanvas.getContext('2d').drawImage(image,sourceX,sourceY,side,side,0,0,320,320);for(const quality of [.82,.7,.58,.46]){const blob=await withTimeout(noteCanvasBlob(photoCanvas,quality),10000,'image-timeout');if(blob&&blob.size<=150000)return new Uint8Array(await blob.arrayBuffer())}throw new Error('profile-photo-large')}
async function saveProfilePhoto(bytes){await updateDoc(doc(db,'users',currentUser.uid),{photo:Bytes.fromUint8Array(bytes),photoType:bytes.length?'image/jpeg':''})}
function authErrorText(error){const messages={'auth/email-already-in-use':'Этот email уже зарегистрирован. Войдите существующим способом.','auth/account-exists-with-different-credential':'Этот email уже зарегистрирован другим способом.','auth/invalid-credential':'Неверный email или пароль.','auth/invalid-email':'Проверьте написание email.','auth/weak-password':'Пароль должен содержать не менее 6 символов.','auth/popup-closed-by-user':'Окно входа было закрыто.','auth/popup-blocked':'Браузер заблокировал окно входа. Разрешите всплывающие окна.','auth/unauthorized-domain':'Этот адрес сайта еще не разрешен в настройках Firebase.','auth/too-many-requests':'Слишком много попыток. Подождите несколько минут.'};return messages[error.code]||'Не удалось выполнить вход. Проверьте интернет и повторите.'}
function setAuthMode(mode){authMode=mode;document.querySelectorAll('[data-auth-mode]').forEach(button=>button.classList.toggle('active',button.dataset.authMode===mode));$('authTitle').textContent=mode==='login'?'Вход':'Регистрация';$('authLead').textContent=mode==='login'?'Войдите, чтобы работать с общими ориентировками.':'Создайте учетную запись. Доступ подтвердит администратор.';$('emailAuthBtn').textContent=mode==='login'?'Войти':'Зарегистрироваться';$('resetPasswordBtn').hidden=mode!=='login';$('authPassword').autocomplete=mode==='login'?'current-password':'new-password';$('authMessage').textContent=''}
function showSignedOut(){document.body.className='auth-signed-out';$('authGate').hidden=false;$('authPanel').hidden=false;$('pendingPanel').hidden=true;$('userTools').hidden=true;$('manageUsersBtn').hidden=true;closeMenu();setAuthMode('login')}
function showPending(user){document.body.className='auth-pending';$('authGate').hidden=false;$('authPanel').hidden=true;$('pendingPanel').hidden=false;$('pendingName').textContent=user.displayName||'Новый пользователь';$('pendingEmail').textContent=user.email||'';$('pendingMessage').textContent=''}
function showReady(user,profile){const isAdmin=profile.role==='admin',isOwner=isAdmin&&(user.email||'').toLowerCase()===OWNER_EMAIL,usersMode=isAdmin?'admin':'member';document.body.className='auth-ready';$('authGate').hidden=true;$('userTools').hidden=false;renderCurrentProfile();renderHome();$('manageUsersBtn').hidden=!isAdmin;$('saveCaseBtn').hidden=!isAdmin;subscribeCases();if(usersSubscriptionMode!==usersMode)stopUsersSubscription();subscribeUsers();if(currentCaseId)openCase(currentCaseId);$('manageUsersBtn').title=isOwner?'Управление пользователями и администраторами':'Управление доступом пользователей'}
async function ensureProfile(user){const ref=doc(db,'users',user.uid),snapshot=await getDoc(ref);if(!snapshot.exists()){const isOwner=(user.email||'').toLowerCase()===OWNER_EMAIL;await setDoc(ref,{email:user.email||'',displayName:user.displayName||(user.email||'').split('@')[0],approved:isOwner,role:isOwner?'admin':'member',createdAt:serverTimestamp()})}return ref}
function stopCaseSubscription(){stopNotesSubscription();stopTracksSubscription();if(unsubscribeCases){unsubscribeCases();unsubscribeCases=null}posterUrls.forEach(URL.revokeObjectURL);posterUrls=[];savedCases=[];renderMenu()}
function stopUsersSubscription(){if(unsubscribeUsers){unsubscribeUsers();unsubscribeUsers=null}usersSubscriptionMode=null;profilePhotoUrls.forEach(URL.revokeObjectURL);profilePhotoUrls=[];userProfiles.clear();$('pendingUsersCount').hidden=true}
function subscribeCases(){if(unsubscribeCases)return;unsubscribeCases=onSnapshot(query(collection(db,'cases'),orderBy('createdAt','desc')),snapshot=>{posterUrls.forEach(URL.revokeObjectURL);posterUrls=[];savedCases=snapshot.docs.map(entry=>{const data=entry.data(),posterBytes=data.poster?.toUint8Array?.()||new Uint8Array();const poster=posterBytes.length?URL.createObjectURL(new Blob([posterBytes],{type:'image/jpeg'})):'';if(poster)posterUrls.push(poster);return{id:entry.id,...data,poster,posterBytes,createdAt:data.createdAt?.toMillis?.()||0,archivedAtMs:data.archivedAt?.toMillis?.()||0}});renderMenu();if(currentCaseId){const current=savedCases.find(item=>item.id===currentCaseId);if(current?.archiveUrl)showCreation(true);else if(current)openCase(currentCaseId);else showHome(true)}else route();maybeOpenSharedTracks()},error=>{console.error(error);$('message').textContent='Не удалось загрузить общие ориентировки.'})}
function subscribeUsers(){if(unsubscribeUsers)return;usersSubscriptionMode=currentIsAdmin()?'admin':'member';const source=usersSubscriptionMode==='admin'?collection(db,'users'):query(collection(db,'users'),where('approved','==',true));unsubscribeUsers=onSnapshot(source,snapshot=>{profilePhotoUrls.forEach(URL.revokeObjectURL);profilePhotoUrls=[];const users=snapshot.docs.map(entry=>{const user={id:entry.id,...entry.data()},bytes=profileBytes(user);if(bytes.length){user.photoUrl=URL.createObjectURL(new Blob([bytes],{type:user.photoType||'image/jpeg'}));profilePhotoUrls.push(user.photoUrl)}return user}).sort((a,b)=>Number(a.approved)-Number(b.approved)||String(a.displayName).localeCompare(String(b.displayName),'ru'));userProfiles=new Map(users.map(user=>[user.id,user]));renderNotes();renderTracks();if(currentIsAdmin()){renderUsers(users);const pending=users.filter(user=>!user.approved).length;$('pendingUsersCount').textContent=String(pending);$('pendingUsersCount').hidden=pending===0}else $('pendingUsersCount').hidden=true},error=>console.error(error))}
function adminShieldIcon(){const namespace='http://www.w3.org/2000/svg',icon=document.createElementNS(namespace,'svg'),shield=document.createElementNS(namespace,'path'),check=document.createElementNS(namespace,'path');icon.setAttribute('viewBox','0 0 24 24');icon.setAttribute('aria-hidden','true');shield.setAttribute('d','M20 13c0 5-3.5 7.5-8 9-4.5-1.5-8-4-8-9V5l8-3 8 3Z');check.setAttribute('d','m9 12 2 2 4-4');icon.append(shield,check);return icon}
function approveIcon(){const namespace='http://www.w3.org/2000/svg',icon=document.createElementNS(namespace,'svg'),check=document.createElementNS(namespace,'path');icon.setAttribute('viewBox','0 0 24 24');icon.setAttribute('aria-hidden','true');check.setAttribute('d','m5 12 4 4L19 6');icon.append(check);return icon}
function trashIcon(){const namespace='http://www.w3.org/2000/svg',icon=document.createElementNS(namespace,'svg'),lid=document.createElementNS(namespace,'path'),bin=document.createElementNS(namespace,'path'),lines=document.createElementNS(namespace,'path');icon.setAttribute('viewBox','0 0 24 24');icon.setAttribute('aria-hidden','true');lid.setAttribute('d','M3 6h18');bin.setAttribute('d','M8 6V4h8v2m3 0-1 15H6L5 6');lines.setAttribute('d','M10 11v6m4-6v6');icon.append(lid,bin,lines);return icon}
function renderUsers(users){
  const list=$('usersList'),owner=currentIsOwner();
  list.replaceChildren();
  if(!users.length){list.textContent='Зарегистрированных пользователей пока нет.';return}
  users.forEach(user=>{
    const isAdmin=user.role==='admin',row=document.createElement('div');
    row.className='user-row'+(isAdmin?' user-row-admin':'')+(!user.approved?' user-row-pending':'');
    const info=document.createElement('div');
    info.className='user-info';
    const name=document.createElement('strong');
    name.textContent=user.displayName||'Без имени';
    const email=document.createElement('span');
    email.textContent=user.email||'';
    info.append(name,email);
    const state=document.createElement('div');
    state.className='user-state';
    const badge=document.createElement('span'),isProfileOwner=(user.email||'').toLowerCase()===OWNER_EMAIL,isSelf=user.id===currentUser?.uid;
    badge.className=isProfileOwner?'approval owner':isAdmin?'approval admin':user.approved?'approval approved':'approval pending';
    if(isAdmin&&!isProfileOwner)badge.append(adminShieldIcon(),document.createTextNode('Администратор'));
    else badge.textContent=isProfileOwner?'Владелец':user.approved?'Доступ открыт':'Ожидает';
    state.append(badge);
    if(!isSelf&&!isProfileOwner&&(user.role==='member'||owner)){
      if(user.role==='member'){
        const access=document.createElement('button');
        access.type='button';
        access.className=user.approved?'ghost small':'pending-approve';
        if(user.approved)access.textContent='Закрыть доступ';
        else{
          access.title='Подтвердить пользователя';
          access.setAttribute('aria-label',`Подтвердить пользователя ${user.displayName||user.email||'Без имени'}`);
          access.append(approveIcon());
        }
        access.onclick=async()=>{access.disabled=true;try{await updateDoc(doc(db,'users',user.id),{approved:!user.approved})}catch(error){console.error(error);access.disabled=false}};
        state.append(access);
        if(!user.approved){
          const remove=document.createElement('button');
          remove.type='button';
          remove.className='pending-delete';
          remove.title='Удалить заявку';
          remove.setAttribute('aria-label',`Удалить заявку пользователя ${user.displayName||user.email||'Без имени'}`);
          remove.append(trashIcon());
          remove.onclick=()=>askConfirmation({title:'Удалить заявку и учетную запись?',text:`Заявка пользователя «${user.displayName||user.email||'Без имени'}» будет удалена из базы и Firebase Authentication. При необходимости пользователь сможет зарегистрироваться заново.`,label:'Удалить полностью',action:async()=>{remove.disabled=true;$('usersMessage').textContent='Удаляю заявку и учетную запись…';try{await deleteAuthenticationUser(user.id);await deleteDoc(doc(db,'users',user.id));$('usersMessage').textContent=''}catch(error){console.error(error);remove.disabled=false;$('usersMessage').textContent=error.userMessage||'Не удалось полностью удалить пользователя. Повторите попытку.'}}});
          state.append(remove);
        }
      }
      if(owner&&(user.approved||user.role==='admin')){
        const role=document.createElement('button');
        role.type='button';
        role.className=user.role==='admin'?'demote-admin small':'secondary small';
        role.textContent=user.role==='admin'?'Снять права администратора':'Назначить администратором';
        role.disabled=user.role!=='admin'&&!user.approved;
        role.onclick=()=>askConfirmation({title:user.role==='admin'?'Снять права администратора?':'Назначить администратором?',text:`Пользователь «${user.displayName||user.email||'Без имени'}» ${user.role==='admin'?'перейдёт в режим просмотра и сохранит доступ только к своим заметкам.':'сможет создавать, удалять и архивировать ориентировки, управлять пользователями и всеми заметками.'}`,label:user.role==='admin'?'Снять права':'Назначить',kind:'primary',action:async()=>{try{await updateDoc(doc(db,'users',user.id),{role:user.role==='admin'?'member':'admin',approved:true})}catch(error){console.error(error)}}});
        state.append(role);
      }
    }
    row.append(info,state);
    list.append(row);
  });
}
async function handleAuthenticatedUser(user){currentUser=user;try{const ref=await ensureProfile(user);if(unsubscribeProfile)unsubscribeProfile();unsubscribeProfile=onSnapshot(ref,snapshot=>{currentProfile=snapshot.data();if(currentProfile?.approved)showReady(user,currentProfile);else{stopCaseSubscription();stopUsersSubscription();showPending(user)}},error=>{console.error(error);showPending(user);$('pendingMessage').textContent='Не удалось проверить доступ. Обновите страницу.'})}catch(error){console.error(error);showPending(user);$('pendingMessage').textContent='Не удалось завершить регистрацию. Обновите страницу.'}}
async function logout(){if(unsubscribeProfile){unsubscribeProfile();unsubscribeProfile=null}stopCaseSubscription();stopUsersSubscription();if(currentProfilePhotoUrl){URL.revokeObjectURL(currentProfilePhotoUrl);currentProfilePhotoUrl=null}currentUser=null;currentProfile=null;await signOut(auth)}

IDS.forEach(id=>{const el=$(id);el.addEventListener('input',()=>renderPreservingFocus(el));el.addEventListener('keydown',e=>{if(e.key==='Enter'&&el.tagName!=='TEXTAREA')e.preventDefault()})});$('previewBtn').onclick=openPreview;$('saveCaseBtn').onclick=openSearchTypeDialog;$('clearBtn').onclick=()=>{if(confirm('Очистить все введённые данные?'))resetForm()};
$('menuBtn').onclick=toggleMenu;$('homeViewBtn').onclick=()=>showHome(true);$('createViewBtn').onclick=()=>showCreation(true);document.addEventListener('click',event=>{if(!$('menuWrap').contains(event.target))closeMenu()});
$('themeToggle').onchange=event=>applyTheme(event.target.checked?'dark':'light');
$('homeCreateCaseBtn').onclick=()=>showCreation(true);$('homePdfBtn').onclick=()=>showCreation(true);$('homeActiveBtn').onclick=()=>toggleHomeSection('active');$('homeArchiveBtn').onclick=()=>toggleHomeSection('archive');document.querySelectorAll('[data-home-menu-status]').forEach(button=>button.onclick=()=>toggleHomeSection(button.dataset.homeMenuStatus,button.dataset.homeMenuType||'',true));document.querySelectorAll('[data-home-close]').forEach(button=>button.onclick=()=>toggleHomeSection(button.dataset.homeClose));
document.querySelectorAll('[data-search-type]').forEach(button=>button.onclick=()=>{$('searchTypeDialog').close();createSavedCase(button.dataset.searchType)});
$('confirmCancelBtn').onclick=()=>{$('confirmDialog').close();pendingConfirm=null};$('confirmAcceptBtn').onclick=()=>{const action=pendingConfirm;pendingConfirm=null;$('confirmDialog').close();if(action)action()};
$('sharedTracksCloseBtn').onclick=closeSharedTracks;$('sharedTracksCancelBtn').onclick=closeSharedTracks;$('sharedTracksDialog').addEventListener('cancel',event=>{event.preventDefault();closeSharedTracks()});$('sharedTracksUploadBtn').onclick=async()=>{const caseId=$('sharedTracksCaseSelect').value;if(!caseId)return;const button=$('sharedTracksUploadBtn'),files=[...sharedTracksFiles];button.disabled=true;$('sharedTracksDialog').close();openCase(caseId,true);await uploadTracks(files);await cleanupSharedTracks();button.disabled=false};
$('deleteCaseBtn').onclick=deleteCurrentCase;$('archiveCaseBtn').onclick=archiveCurrentCase;window.addEventListener('popstate',route);
$('saveNoteBtn').onclick=saveNote;$('cancelNoteEditBtn').onclick=()=>resetNoteComposer();$('removeNoteImageBtn').onclick=()=>{releaseEditorImage();renderNoteAttachment()};
$('trackFilesInput').onchange=event=>uploadTracks(event.target.files);
$('notePhotoInput').onchange=async event=>{const file=event.target.files[0];if(!file)return;$('noteMessage').textContent='Подготавливаю фотографию…';try{const bytes=await compressNotePhoto(file);setEditorImage(bytes);$('noteMessage').textContent='Фотография добавлена.'}catch(error){console.error(error);$('noteMessage').textContent=noteErrorText(error);event.target.value=''}};
document.querySelectorAll('[data-note-command]').forEach(button=>{button.onmousedown=event=>event.preventDefault();button.onclick=()=>{document.execCommand(button.dataset.noteCommand,false,null);$('noteEditor').focus()}});
$('logoutBtn').onclick=logout;$('pendingLogoutBtn').onclick=logout;$('pendingRefreshBtn').onclick=async()=>{if(!currentUser)return;$('pendingMessage').textContent='Проверяю…';try{const snapshot=await getDoc(doc(db,'users',currentUser.uid));$('pendingMessage').textContent=snapshot.data()?.approved?'Доступ открыт. Загружаю данные…':'Подтверждения пока нет.'}catch{$('pendingMessage').textContent='Не удалось проверить доступ.'}};
$('profileMenuBtn').onclick=openProfile;$('profileCloseBtn').onclick=()=>$('profileDialog').close();
$('profileNameForm').onsubmit=async event=>{event.preventDefault();const name=$('profileName').value.trim();if(name.length<2){setProfileMessage('Имя должно содержать не менее 2 символов.');$('profileName').focus();return}const button=$('profileNameSaveBtn');button.disabled=true;setProfileMessage('Сохраняю имя…');try{await updateDoc(doc(db,'users',currentUser.uid),{displayName:name});try{await updateProfile(currentUser,{displayName:name})}catch(error){console.error(error)}setProfileMessage('Имя сохранено.',true)}catch(error){console.error(error);setProfileMessage(profileErrorText(error))}finally{button.disabled=false}};
$('profilePhotoInput').onchange=async event=>{const file=event.target.files[0];if(!file)return;setProfileMessage('Подготавливаю фотографию…');try{const bytes=await compressProfilePhoto(file);setProfileMessage('Сохраняю фотографию…');await saveProfilePhoto(bytes);setProfileMessage('Фотография сохранена.',true)}catch(error){console.error(error);if(error.message==='profile-photo-source-large')setProfileMessage('Исходный файл больше 10 МБ. Выберите другое фото.');else if(error.message==='profile-photo-large'||error.message==='image-timeout')setProfileMessage('Не удалось подготовить фотографию. Выберите другое фото.');else setProfileMessage(profileErrorText(error))}finally{event.target.value=''}};
$('removeProfilePhotoBtn').onclick=async()=>{const button=$('removeProfilePhotoBtn');button.disabled=true;setProfileMessage('Удаляю фотографию…');try{await saveProfilePhoto(new Uint8Array());setProfileMessage('Фотография удалена.',true)}catch(error){console.error(error);setProfileMessage(profileErrorText(error))}finally{button.disabled=false}};
$('profilePasswordForm').onsubmit=async event=>{event.preventDefault();const password=$('profileNewPassword').value,confirmation=$('profileConfirmPassword').value;if(password!==confirmation){setProfileMessage('Пароли не совпадают.');$('profileConfirmPassword').focus();return}const button=$('profilePasswordSaveBtn');button.disabled=true;setProfileMessage('Изменяю пароль…');try{await updatePassword(currentUser,password);$('profileNewPassword').value='';$('profileConfirmPassword').value='';setProfileMessage('Пароль изменен.',true)}catch(error){console.error(error);setProfileMessage(profileErrorText(error))}finally{button.disabled=false}};
$('linkEmailForm').onsubmit=async event=>{event.preventDefault();const password=$('linkEmailPassword').value,confirmation=$('linkEmailPasswordConfirm').value;if(password!==confirmation){setProfileMessage('Пароли не совпадают.');$('linkEmailPasswordConfirm').focus();return}const button=$('linkEmailBtn');button.disabled=true;setProfileMessage('Подключаю вход по почте…');try{const credential=EmailAuthProvider.credential(currentUser.email,password);await linkWithCredential(currentUser,credential);await currentUser.reload();currentUser=auth.currentUser;$('linkEmailPassword').value='';$('linkEmailPasswordConfirm').value='';renderProfileProviders();setProfileMessage('Вход по почте подключен.',true)}catch(error){console.error(error);setProfileMessage(profileErrorText(error))}finally{button.disabled=false}};
$('linkGoogleBtn').onclick=async()=>{const button=$('linkGoogleBtn');button.disabled=true;setProfileMessage('Открываю Google…');try{const credential=await linkWithPopup(currentUser,googleProvider);currentUser=credential.user;renderProfileProviders();setProfileMessage('Вход через Google подключен.',true)}catch(error){console.error(error);setProfileMessage(profileErrorText(error))}finally{button.disabled=false}};
$('manageUsersBtn').onclick=()=>{$('usersDialog').showModal()};$('closeUsersBtn').onclick=()=>{$('usersDialog').close()};
document.querySelectorAll('[data-auth-mode]').forEach(button=>button.onclick=()=>setAuthMode(button.dataset.authMode));
$('googleAuthBtn').onclick=async()=>{$('authMessage').textContent='Открываю вход через Google…';try{await signInWithPopup(auth,googleProvider)}catch(error){console.error(error);if(error.code==='auth/account-exists-with-different-credential'){pendingGoogleCredential=GoogleAuthProvider.credentialFromError(error);setAuthMode('login');$('authEmail').value=error.customData?.email||'';$('authMessage').textContent='Этот email уже зарегистрирован. Введите пароль: после входа Google будет подключен к той же учетной записи.'}else $('authMessage').textContent=authErrorText(error)}};
$('emailAuthForm').onsubmit=async event=>{event.preventDefault();const email=$('authEmail').value.trim(),password=$('authPassword').value;$('emailAuthBtn').disabled=true;$('authMessage').textContent=authMode==='login'?'Выполняю вход…':'Создаю учетную запись…';try{if(authMode==='login'){const credential=await signInWithEmailAndPassword(auth,email,password);if(pendingGoogleCredential){await linkWithCredential(credential.user,pendingGoogleCredential);pendingGoogleCredential=null}}else{const credential=await createUserWithEmailAndPassword(auth,email,password);await updateProfile(credential.user,{displayName:email.split('@')[0]})}}catch(error){console.error(error);$('authMessage').textContent=authErrorText(error)}finally{$('emailAuthBtn').disabled=false}};
$('resetPasswordBtn').onclick=async()=>{const email=$('authEmail').value.trim();if(!email){$('authMessage').textContent='Сначала укажите email.';$('authEmail').focus();return}try{await sendPasswordResetEmail(auth,email);$('authMessage').textContent='Письмо для восстановления пароля отправлено.'}catch(error){console.error(error);$('authMessage').textContent=authErrorText(error)}};
$('photo').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=ev=>{photoImg=new Image();photoImg.onload=()=>{render();$('photoThumb').src=ev.target.result;$('photoThumb').hidden=false};photoImg.src=ev.target.result};r.readAsDataURL(f)};
$('pdfBtn').onclick=()=>{render();const jpg=canvas.toDataURL('image/jpeg',.96);const win=window.open('','_blank');if(!win){$('message').textContent='Браузер заблокировал окно печати. Разрешите всплывающие окна.';return}win.document.write(`<html><head><title>Ориентировка</title><style>@page{size:A4 portrait;margin:0}html,body{margin:0;width:100%;height:100%;display:flex;align-items:center;justify-content:center;background:#fff}img{width:198mm;height:auto;max-height:297mm;display:block}</style></head><body><img src="${jpg}" onload="setTimeout(()=>window.print(),300)"></body></html>`);win.document.close();$('message').textContent='В окне печати выберите «Сохранить как PDF».'};
const INSTALL_MARKER='kpc-app-installed';
function installationMarked(){try{return localStorage.getItem(INSTALL_MARKER)==='1'}catch{return false}}
function markInstallation(installed){try{if(installed)localStorage.setItem(INSTALL_MARKER,'1');else localStorage.removeItem(INSTALL_MARKER)}catch{}}
function isStandalone(){return window.matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}
async function updateInstallButton(){let installed=isStandalone()||installationMarked();if(isStandalone())markInstallation(true);if(!installed&&'getInstalledRelatedApps'in navigator){try{installed=(await navigator.getInstalledRelatedApps()).length>0;if(installed)markInstallation(true)}catch{}}$('installBtn').hidden=installed}
function net(){const on=navigator.onLine;$('netStatus').textContent=on?'Онлайн':'Офлайн';$('netStatus').className='badge '+(on?'online':'offline')}
window.addEventListener('online',net);window.addEventListener('offline',net);
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredPrompt=event;markInstallation(false);$('installBtn').hidden=false});
window.addEventListener('appinstalled',()=>{deferredPrompt=null;markInstallation(true);$('installBtn').hidden=true});
$('installBtn').onclick=async()=>{if(!deferredPrompt){alert('Откройте меню Chrome и выберите «Установить приложение». Если приложение уже установлено, откройте его через меню приложений Chrome.');return}deferredPrompt.prompt();const choice=await deferredPrompt.userChoice;deferredPrompt=null;if(choice.outcome==='accepted'){markInstallation(true);$('installBtn').hidden=true}};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));if(document.fonts)document.fonts.ready.then(render);applyTheme(initialTheme());load();renderMenu();renderTracks();net();updateInstallButton();setPersistence(auth,browserLocalPersistence).catch(console.error);onAuthStateChanged(auth,user=>{if(user)handleAuthenticatedUser(user);else{if(unsubscribeProfile){unsubscribeProfile();unsubscribeProfile=null}stopCaseSubscription();stopUsersSubscription();currentUser=null;currentProfile=null;showSignedOut()}});
