const IDS=['lastName','firstMiddleName','age','date','place','height','build','hair','eyes','special','jacket','pants','shoes','carrying','actual'];
const $=id=>document.getElementById(id); const canvas=$('poster'),ctx=canvas.getContext('2d');
let bg=new Image(),photoImg=null,deferredPrompt=null; bg.src='template.jpg'; bg.onload=render;
function val(id){return $(id).value.trim()} function save(){const d={};IDS.forEach(id=>d[id]=$(id).value);localStorage.setItem('kpc-draft',JSON.stringify(d))}
function load(){try{const d=JSON.parse(localStorage.getItem('kpc-draft')||'{}');IDS.forEach(id=>{if(d[id]!=null)$(id).value=d[id]})}catch{} if(!val('actual')) $('actual').value=new Date().toISOString().slice(0,10)}
function formatDate(s){if(!s)return'';const p=s.split('-');return p.length===3?`${p[2]}.${p[1]}.${p[0]}`:s}
function fitText(text,x,y,maxW,start=66,min=30,weight=700){ctx.font=`${weight} ${start}px Arial`;let size=start;while(ctx.measureText(text).width>maxW&&size>min){size-=2;ctx.font=`${weight} ${size}px Arial`}ctx.fillText(text,x,y)}
function wrap(text,x,y,maxW,lineH,font='38px Arial',maxLines=3){ctx.font=font;const words=(text||'').split(/\s+/);let line='',lines=[];for(const w of words){const t=line?line+' '+w:w;if(ctx.measureText(t).width>maxW&&line){lines.push(line);line=w}else line=t}if(line)lines.push(line);lines.slice(0,maxLines).forEach((l,i)=>ctx.fillText(l,x,y+i*lineH))}
function bullet(label,value,x,y,maxW){if(!value)return;ctx.fillStyle='#111';ctx.font='700 27px Arial';ctx.fillText('• '+label+':',x,y);const off=ctx.measureText('• '+label+': ').width;ctx.font='27px Arial';wrap(value,x+off,y,maxW-off,34,'27px Arial',2)}
function render(){if(!bg.complete)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(bg,0,0,canvas.width,canvas.height);if(photoImg){const x=51,y=336,w=535,h=678;const ir=photoImg.width/photoImg.height,br=w/h;let sx=0,sy=0,sw=photoImg.width,sh=photoImg.height;if(ir>br){sw=photoImg.height*br;sx=(photoImg.width-sw)/2}else{sh=photoImg.width/br;sy=(photoImg.height-sh)/2}ctx.save();roundRect(x,y,w,h,24);ctx.clip();ctx.drawImage(photoImg,sx,sy,sw,sh,x,y,w,h);ctx.restore()}
ctx.fillStyle='#080808';fitText(val('lastName').toUpperCase(),635,482,520,74,38,800);fitText(val('firstMiddleName'),635,548,520,48,28,700);fitText(val('age'),635,630,520,39,26,700);ctx.fillStyle='#c40000';fitText(formatDate(val('date')),925,764,240,33,24,700);ctx.fillStyle='#111';wrap(val('place'),704,856,455,43,'700 34px Arial',3);
bullet('Рост',val('height'),57,1142,500);bullet('Телосложение',val('build'),57,1190,500);bullet('Волосы',val('hair'),57,1238,500);bullet('Глаза',val('eyes'),57,1286,500);bullet('Особые приметы',val('special'),57,1334,500);bullet('Куртка',val('jacket'),632,1142,520);bullet('Брюки',val('pants'),632,1190,520);bullet('Обувь',val('shoes'),632,1238,520);bullet('При себе',val('carrying'),632,1286,520);ctx.fillStyle='#fff';ctx.textAlign='center';fitText(formatDate(val('actual')),690,1736,250,24,18,500);ctx.textAlign='start'}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
IDS.forEach(id=>$(id).addEventListener('input',()=>{save();render()}));$('previewBtn').onclick=render;$('clearBtn').onclick=()=>{if(confirm('Очистить все введённые данные?')){IDS.forEach(id=>$(id).value='');localStorage.removeItem('kpc-draft');photoImg=null;$('photoThumb').hidden=true;$('actual').value=new Date().toISOString().slice(0,10);render()}};
$('photo').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=ev=>{photoImg=new Image();photoImg.onload=()=>{render();$('photoThumb').src=ev.target.result;$('photoThumb').hidden=false};photoImg.src=ev.target.result};r.readAsDataURL(f)};
$('pdfBtn').onclick=()=>{render();const jpg=canvas.toDataURL('image/jpeg',.96);const win=window.open('','_blank');if(!win){$('message').textContent='Браузер заблокировал окно печати. Разрешите всплывающие окна.';return}win.document.write(`<html><head><title>Ориентировка</title><style>@page{size:A4 portrait;margin:0}html,body{margin:0}img{width:210mm;height:297mm;display:block}</style></head><body><img src="${jpg}" onload="setTimeout(()=>window.print(),300)"></body></html>`);win.document.close();$('message').textContent='В окне печати выберите «Сохранить как PDF».'};
function net(){const on=navigator.onLine;$('netStatus').textContent=on?'Онлайн':'Офлайн — приложение работает';$('netStatus').className='badge '+(on?'online':'offline')}window.addEventListener('online',net);window.addEventListener('offline',net);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').hidden=false});$('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').hidden=true}};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));load();net();
